import { createHash, randomUUID } from 'node:crypto';
import path from 'node:path';
import type { Classification, LLMConfig, LLMProvider, ParsedDocument } from '../../core/src/types.js';
import { estimatedModelCost, modelProfile } from '../../llm/src/models.js';
import type { Connection, Database } from '../../knowledge/src/database.js';
import { HttpError, type KnowledgeService } from '../../knowledge/src/service.js';
import { parseDocument } from '../../parsers/src/index.js';
import { chunkDocument, extractiveSummary } from '../../ingestion/src/chunking.js';
import { indexText, queryText } from '../../knowledge/src/search.js';
import { normalizedContentHash } from '../../deduplication/src/detector.js';
import { SceneLabReportAdapter } from './scenelab.js';
import { StructuredService } from '../../structured/src/service.js';
import { engineeringOpticsConflicts } from './optics.js';
import { categoryForType, factProposals, mergeFactProposals, inferFingerprint, mergeWorkspaceRequirements, requirementCategoryLabels, safeRequirements, userFactKey, normalizedRequirement } from './workspace.js';
import type { ManualRequirementNote, ProjectFingerprint, WorkspaceRequirement } from './types.js';
import {normalizeFingerprint,type TagAlias} from '../../knowledge-enrichment/src/taxonomy.js';
import { isHistoricalReconstructionProject,type ReconstructionReview } from './reconstruction.js';
import { buildRequirementRequests, extractRequirementsAI, parseRequirements, requirementEntries, requirementQuestions, stableId, type RequirementSource, type RequirementExtractionOptions } from './requirements.js';
import type { ContextPatch, EngineeringData, LockedFact, Project, ProjectAsset, ProjectConflict, ProjectContext, ProjectInput, ProjectRequirements, SourceReference } from './types.js';

const scope="p.organization_id='default' AND p.workspace_id='default'";
const date=(value:any)=>value instanceof Date?value.toISOString():String(value);
const field=<T>(value:T)=>({value,confidence:1,source:'metadata' as const});
const classification:Classification={documentType:field('contract_or_requirement'),authority:field('reference'),applications:field([]),topics:field([]),products:field([]),language:field('unknown')};
const allowed=new Set(['.docx','.pdf','.xlsx','.xls','.csv','.md','.txt','.scenelab-report']);

export class ProjectService {
 constructor(readonly db:Database,readonly knowledge:KnowledgeService,private providerFactory?: (config:LLMConfig)=>LLMProvider) {}
 private async row(id:string,db:Connection=this.db,lock=false) {const row=(await db.query(`SELECT p.* FROM projects p WHERE p.id=$1 AND ${scope}${lock?' FOR UPDATE':''}`,[id]))[0];if(!row)throw new HttpError(404,'项目不存在');return row;}
 private inputRecord(row:any):ProjectInput{return {id:row.id,projectId:row.project_id,documentId:row.document_id||undefined,kind:row.kind,filename:row.filename,title:row.title,status:row.status,createdAt:date(row.created_at),warnings:row.warnings||[],error:row.error||undefined};}
 private assetRecord(row:any):ProjectAsset{return {id:row.id,projectId:row.project_id,inputId:row.input_id,retiredAt:row.retired_at?date(row.retired_at):undefined,role:row.role,filename:row.filename,mimeType:row.mime_type,objectKey:row.object_key,width:row.width||undefined,height:row.height||undefined,caption:row.caption||undefined,sourceRef:row.source_ref,url:`/api/projects/${row.project_id}/assets/${row.id}`};}
 async list(){const rows=await this.db.query(`SELECT p.id FROM projects p WHERE ${scope} ORDER BY p.updated_at DESC,p.id LIMIT 500`);const items=[];for(const row of rows)items.push(await this.get(row.id));return items;}
 async get(id:string):Promise<Project>{const row=await this.row(id);const inputs=await this.db.query('SELECT * FROM project_inputs WHERE project_id=$1 ORDER BY created_at,id',[id]);const assets=await this.listAssets(id);return {id:row.id,organizationId:row.organization_id,workspaceId:row.workspace_id,name:row.name,customerName:row.customer_name||undefined,description:row.description,companyName:row.company_name,documentType:row.document_type,status:row.status,contextRevision:row.context_revision,confirmedRevision:row.confirmed_revision,createdAt:date(row.created_at),updatedAt:date(row.updated_at),inputs:inputs.map(row=>this.inputRecord(row)),assets};}
 async listAssets(id:string,includeRetired=false):Promise<ProjectAsset[]>{await this.row(id);return (await this.db.query('SELECT * FROM project_assets WHERE project_id=$1 AND ($2::boolean OR retired_at IS NULL) ORDER BY id',[id,includeRetired])).map(row=>this.assetRecord(row));}
 async create(input:{name:string;customerName?:string;description?:string;companyName?:string}) {
  const id=randomUUID();await this.db.query("INSERT INTO projects(id,organization_id,workspace_id,name,customer_name,description,company_name) VALUES($1,'default','default',$2,$3,$4,$5)",[id,input.name.trim(),input.customerName?.trim()||null,input.description||'',input.companyName?.trim()||'上海青瞳视觉科技有限公司']);
  await this.rebuildContext(id);return this.get(id);
 }
 async update(id:string,input:{name?:string;customerName?:string;description?:string;companyName?:string;status?:'archived'|'draft'}) {
  await this.db.transaction(async tx=>{const previous=await this.row(id,tx,true);await tx.query('UPDATE projects SET name=$2,customer_name=$3,description=$4,company_name=$5,status=$6,input_revision=input_revision+1,confirmed_revision=NULL,updated_at=now() WHERE id=$1',[id,input.name??previous.name,input.customerName??previous.customer_name,input.description??previous.description,input.companyName??previous.company_name,input.status??'draft']);await this.audit(tx,id,'project_update',previous,input);});
  if(input.status!=='archived')await this.rebuildContext(id);return this.get(id);
 }
 private async audit(tx:Connection,id:string,action:string,previous:unknown,next:unknown){await tx.query('INSERT INTO project_audit_events(id,project_id,action,previous_value,next_value) VALUES($1,$2,$3,$4::jsonb,$5::jsonb)',[randomUUID(),id,action,JSON.stringify(previous),JSON.stringify(next)]);}

 async addText(id:string,input:{title?:string;text:string}) {return this.addInput(id,{filename:`${(input.title||'手工补充').replace(/[\\/:*?"<>|]/g,'_').slice(0,150)}.txt`,bytes:Buffer.from(input.text),mimeType:'text/plain',kind:'text',title:input.title});}
 async addInput(id:string,input:{filename:string;bytes:Uint8Array;mimeType?:string;kind?:'text';title?:string},replaceInputId?:string):Promise<{input:ProjectInput;context:ProjectContext}> {
  const project=await this.row(id);if(project.status==='archived')throw new HttpError(409,'归档项目不能导入资料');
  const filename=path.basename(input.filename.replace(/\\/g,'/'));const extension=path.extname(filename).toLowerCase();if(!allowed.has(extension))throw new HttpError(400,'不支持此项目资料格式');if(!input.bytes.length||input.bytes.length>80*1024*1024)throw new HttpError(400,'文件为空或超过 80 MB');
  const hash=createHash('sha256').update(input.bytes).digest('hex'),kind=extension==='.scenelab-report'?'engineering':input.kind||'document';
  const existing=(await this.db.query('SELECT * FROM project_inputs WHERE project_id=$1 AND content_hash=$2 AND kind=$3',[id,hash,kind]))[0];if(existing){if(replaceInputId&&existing.id!==replaceInputId)await this.removeInput(id,replaceInputId);return {input:this.inputRecord(existing),context:await this.getContext(id)};}
  const replacedKeys=replaceInputId?await this.ownedKeys(id,replaceInputId):[];
  const inputId=randomUUID(),objectKey=`projects/${id}/inputs/${inputId}/${hash}`;await this.knowledge.storage.put(objectKey,input.bytes);
  let parsed:ParsedDocument|undefined,engineering:EngineeringData|undefined,assets:{asset:ProjectAsset;bytes:Uint8Array}[]=[],warnings:string[]=[],error:string|undefined;
  try {
   if(kind==='engineering'){const result=await new SceneLabReportAdapter().parse(input.bytes,id,inputId,filename);engineering=result.engineering;assets=result.assets;warnings=result.warnings;}
   else {parsed=await parseDocument({buffer:input.bytes,contentHash:hash,meta:{sourceId:'manual',sourceType:'project',filename,mimeType:input.mimeType}});warnings=parsed.parseWarnings;if(parsed.parseStatus==='failed'||!parsed.plainText.trim())throw new HttpError(400,'未能提取正文，请提供可读文档或 OCR 文本');}
  }catch(reason){error=reason instanceof HttpError?reason.message:'项目资料解析失败，请检查格式后重试';}
  if(replaceInputId&&error){await this.cleanupKeys(id,[objectKey]);throw new HttpError(400,`${error}；原资料仍然保留`);}
  const title=input.title||parsed?.title||filename;let committedInputId=inputId;
  try{for(const asset of assets)await this.knowledge.storage.put(asset.asset.objectKey,asset.bytes);await this.db.transaction(async tx=>{
   await this.row(id,tx,true);const concurrent=(await tx.query('SELECT id FROM project_inputs WHERE project_id=$1 AND content_hash=$2 AND kind=$3',[id,hash,kind]))[0];if(concurrent){committedInputId=concurrent.id;if(replaceInputId&&concurrent.id!==replaceInputId)await this.deleteInputRows(tx,id,replaceInputId);return;}
   if(replaceInputId)await this.deleteInputRows(tx,id,replaceInputId);
   let documentId:string|undefined;
   if(parsed&&!error){documentId=randomUUID();const versionId=randomUUID(),sourceId=randomUUID();await tx.query("INSERT INTO source_documents(id,source_id,source_document_id,source_path,content_hash) VALUES($1,'manual',$2,$3,$4)",[sourceId,`project:${id}:${inputId}`,filename,hash]);
    await tx.query("INSERT INTO documents(id,organization_id,workspace_id,scope,project_id,source_document_id,title,canonical_title,status,active_version_id) VALUES($1,'default','default','project',$2,$3,$4,$4,'active',$5)",[documentId,id,sourceId,title,versionId]);
    await tx.query("INSERT INTO document_versions(id,document_id,version_number,filename,mime_type,content_hash,normalized_content_hash,object_key,size_bytes,parsed_document,parse_status,summary,extractive_summary) VALUES($1,$2,1,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$11)",[versionId,documentId,filename,input.mimeType||null,hash,normalizedContentHash(parsed),objectKey,input.bytes.length,JSON.stringify(parsed),parsed.parseStatus,extractiveSummary(parsed.plainText)]);
    for(const [name,value] of Object.entries(classification))await tx.query('INSERT INTO classification_results(version_id,field,value,confidence,source) VALUES($1,$2,$3::jsonb,$4,$5)',[versionId,name,JSON.stringify(value.value),value.confidence,value.source]);
    for(const chunk of chunkDocument(parsed,classification,{targetTokens:1000,overlapTokens:80}))await tx.query("INSERT INTO knowledge_chunks(id,document_id,version_id,chunk_order,heading_path,text,summary,metadata,search_vector) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8::jsonb,to_tsvector('simple',$9))",[randomUUID(),documentId,versionId,chunk.order,JSON.stringify(chunk.headingPath),chunk.text,chunk.summary,JSON.stringify({...chunk.metadata,sourceInputId:inputId,scope:'project',projectId:id}),indexText(`${title} ${chunk.text}`)]);
   }
   await tx.query('INSERT INTO project_inputs(id,project_id,document_id,kind,filename,title,content_hash,object_key,mime_type,status,parsed_document,engineering_data,warnings,error) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13::jsonb,$14)',[inputId,id,documentId||null,kind,filename,title,hash,objectKey,input.mimeType||null,error?'failed':'ready',JSON.stringify(parsed||null),JSON.stringify(engineering||null),JSON.stringify(warnings),error||null]);
   for(const {asset} of assets)await tx.query('INSERT INTO project_assets(id,project_id,input_id,role,filename,mime_type,object_key,width,height,caption,source_ref) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb)',[asset.id,id,inputId,asset.role,asset.filename,asset.mimeType,asset.objectKey,asset.width,asset.height,asset.caption||null,JSON.stringify(asset.sourceRef)]);
   await tx.query("UPDATE projects SET input_revision=input_revision+1,confirmed_revision=NULL,status='draft',updated_at=now() WHERE id=$1",[id]);
   await this.audit(tx,id,'project_input_added',null,{inputId,filename,kind,status:error?'failed':'ready'});
  });}catch(error){await this.cleanupKeys(id,[objectKey,...assets.map(a=>a.asset.objectKey)]);throw error;}
  await this.cleanupKeys(id,[...replacedKeys,...(committedInputId!==inputId?[objectKey,...assets.map(a=>a.asset.objectKey)]:[])]);
  const context=await this.rebuildContext(id);const row=(await this.db.query('SELECT * FROM project_inputs WHERE id=$1 AND project_id=$2',[committedInputId,id]))[0];return {input:this.inputRecord(row),context};
 }

 private async ownedKeys(id:string,inputId?:string){return (await this.db.query('SELECT object_key FROM project_inputs WHERE project_id=$1 AND ($2::text IS NULL OR id=$2) UNION SELECT object_key FROM project_assets WHERE project_id=$1 AND ($2::text IS NULL OR input_id=$2)',[id,inputId||null])).map(r=>String(r.object_key));}
 private async cleanupKeys(id:string,keys:string[]){if(!this.knowledge.storage.delete)return;for(const key of new Set(keys)){if(!key.startsWith(`projects/${id}/`))continue;const referenced=await this.db.query('SELECT object_key FROM project_inputs WHERE object_key=$1 UNION SELECT object_key FROM project_assets WHERE object_key=$1 UNION SELECT object_key FROM document_versions WHERE object_key=$1',[key]);if(!referenced.length)await this.knowledge.storage.delete(key);}}
 private async invalidate(tx:Connection,id:string){await tx.query("UPDATE projects SET input_revision=input_revision+1,confirmed_revision=NULL,status='draft',updated_at=now() WHERE id=$1",[id]);}
 async listNotes(id:string):Promise<ManualRequirementNote[]>{await this.row(id);return (await this.db.query('SELECT * FROM project_manual_notes WHERE project_id=$1 ORDER BY created_at,id',[id])).map(r=>({id:r.id,projectId:r.project_id,title:r.title,text:r.text,status:r.status,createdAt:date(r.created_at),updatedAt:date(r.updated_at)}));}
 async saveNote(id:string,input:{title?:string;text:string;status?:'active'|'archived';analyze?:boolean},noteId?:string){const key=noteId||randomUUID();await this.db.transaction(async tx=>{await this.row(id,tx,true);const previous=noteId?(await tx.query('SELECT * FROM project_manual_notes WHERE id=$1 AND project_id=$2',[noteId,id]))[0]:null;if(noteId&&!previous)throw new HttpError(404,'补充说明不存在');await tx.query('INSERT INTO project_manual_notes(id,project_id,title,text,status) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET title=excluded.title,text=excluded.text,status=excluded.status,updated_at=now()',[key,id,input.title||'补充说明',input.text,input.status||'active']);await this.invalidate(tx,id);await this.audit(tx,id,'note_saved',previous,{noteId:key,title:input.title||'补充说明',text:input.text,status:input.status||'active'});});const context=await this.rebuildContext(id,{useAI:input.analyze===true,model:'kimi-k3'});return {note:(await this.listNotes(id)).find(n=>n.id===key)!,context};}
 async removeNote(id:string,noteId:string){await this.db.transaction(async tx=>{await this.row(id,tx,true);const rows=await tx.query('DELETE FROM project_manual_notes WHERE id=$1 AND project_id=$2 RETURNING *',[noteId,id]);if(!rows.length)throw new HttpError(404,'补充说明不存在');await this.audit(tx,id,'note_removed',rows[0],null);await this.invalidate(tx,id);});return this.rebuildContext(id);}
 async saveFingerprint(id:string,fingerprint:ProjectFingerprint){await this.db.transaction(async tx=>{await this.row(id,tx,true);fingerprint=normalizeFingerprint(fingerprint,await tx.query<TagAlias>('SELECT dimension,alias,canonical FROM knowledge_tag_aliases'));await tx.query('UPDATE projects SET fingerprint=$2::jsonb WHERE id=$1',[id,JSON.stringify(fingerprint)]);await this.invalidate(tx,id);});return this.rebuildContext(id);}
 async addRequirement(id:string,input:{type:string;label:string;value:unknown;unit?:string;notes?:string}){const category=categoryForType[input.type]||'specialRequirements';const semanticKey=category.startsWith('performance.')?category:`${category}:${normalizedRequirement(input.value,input.unit)}`;const row:WorkspaceRequirement={id:stableId(id,'requirement',semanticKey),semanticKey,category,label:input.label||requirementCategoryLabels[category],value:input.value,unit:input.unit,status:'confirmed',confirmedByUser:true,evidenceRefs:[{sourceType:'user',sourceId:id,excerpt:`${input.label}：${String(input.value)}${input.unit||''}${input.notes?`；${input.notes}`:''}`}]};return this.saveDecision(id,row);}
 private async saveDecision(id:string,row:WorkspaceRequirement){await this.db.transaction(async tx=>{await this.row(id,tx,true);await tx.query('INSERT INTO project_requirement_decisions(id,project_id,semantic_key,decision) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(project_id,semantic_key) DO UPDATE SET decision=excluded.decision,updated_at=now()',[row.id,id,row.semanticKey,JSON.stringify(row)]);await this.invalidate(tx,id);});return this.rebuildContext(id);}
 async decideRequirement(id:string,requirementId:string,input:{choice?:number;status?:'unknown'|'not_applicable';value?:unknown}){const context=await this.getContext(id),row=context.workspaceRequirements?.find(r=>r.id===requirementId);if(!row)throw new HttpError(404,'客户要求不存在');let value=input.value??row.value;if(input.choice!==undefined){const selected=row.alternatives?.[input.choice];if(!selected)throw new HttpError(400,'请选择有效的来源值');value=selected.value;}return this.saveDecision(id,{...row,value,status:input.status||'confirmed',confirmedByUser:true,evidenceRefs:[...row.evidenceRefs,{sourceType:'user',sourceId:id,excerpt:input.status?'用户选择暂不采用具体值':`用户采用：${String(value)}`}]});}
 async clearRequirementValue(id:string,requirementId:string){const context=await this.getContext(id),row=context.workspaceRequirements?.find(r=>r.id===requirementId);if(!row)throw new HttpError(404,'客户要求不存在');await this.db.transaction(async tx=>{await this.row(id,tx,true);await tx.query('DELETE FROM project_requirement_decisions WHERE project_id=$1 AND semantic_key=$2',[id,row.semanticKey]);await this.invalidate(tx,id);});return this.rebuildContext(id,{resetRequirementId:requirementId,restoreCategories:[row.category]});}
 async removeFact(id:string,factId:string){await this.db.transaction(async tx=>{await this.row(id,tx,true);if(!(await tx.query("DELETE FROM project_facts WHERE project_id=$1 AND id=$2 AND source_type='user' RETURNING id",[id,factId])).length)throw new HttpError(404,'人工事实不存在，工程结果需替换或删除报告');await this.invalidate(tx,id);});return this.rebuildContext(id);}
 async addFact(id:string,input:{label:string;value:unknown;unit?:string;category?:string;proposalId?:string}){const context=await this.getContext(id);const proposal=input.proposalId?context.factProposals?.find(p=>p.id===input.proposalId):undefined;if(input.proposalId&&!proposal)throw new HttpError(404,'待确认事实不存在');const key=proposal?.key||userFactKey(input.label,input.category||'其他',input.value);let value=input.value;if(key==='deployment.equipmentCount'&&typeof value==='string')value=Number(value.replace(/\s*台\s*$/,''));if(key==='scene.boundaryM'&&typeof value==='string'){const numbers=value.match(/\d+(?:\.\d+)?/g);if(numbers?.length===3)value=numbers.map(Number);}if(key==='products')return this.patchContext(id,{revision:context.revision,products:Array.isArray(value)?value.map(String):String(value).split(/[,，、\n]/).map(v=>v.trim()).filter(Boolean)});return this.patchContext(id,{revision:context.revision,facts:[{key,label:input.label,value,unit:input.unit,evidenceRefs:proposal?.evidenceRefs}]});}
 async answerClarification(id:string,questionId:string,input:{mode:'answer'|'unknown'|'not_applicable'|'conventional';value?:string}){const context=await this.getContext(id),question=context.requirements.unresolved.find(q=>q.id===questionId)||context.unresolved.find(q=>q.id===questionId);if(!question)throw new HttpError(404,'该问题已解决或不存在');if(input.mode==='answer'&&!input.value?.trim())throw new HttpError(400,'请填写答案');if(input.mode==='answer'&&(question.target==='project_fact.camera_count'||question.key==='cameraCount')){const n=Number(input.value!.replace(/\s*台\s*$/,''));if(!Number.isInteger(n)||n<0||n>10000)throw new HttpError(400,'相机数量请填写 0–10000 的整数');}await this.db.transaction(async tx=>{await this.row(id,tx,true);await tx.query('INSERT INTO project_clarification_answers(project_id,question_id,answer) VALUES($1,$2,$3::jsonb) ON CONFLICT(project_id,question_id) DO UPDATE SET answer=excluded.answer,updated_at=now()',[id,questionId,JSON.stringify(input)]);await this.invalidate(tx,id);});if(input.mode==='answer'){if(question.target==='project_fact.camera_count'||question.key==='cameraCount'){const n=Number(input.value!.replace(/\s*台\s*$/,''));if(!Number.isInteger(n)||n<0||n>10000)throw new HttpError(400,'相机数量请填写 0–10000 的整数');await this.rebuildContext(id);return this.addFact(id,{label:'相机数量',value:n,unit:'台',category:'设备'});}return this.addRequirement(id,{type:question.key==='protocol'?'interface':question.key,label:requirementCategoryLabels[`performance.${question.key}`]||question.question,value:input.value!});}return this.rebuildContext(id);}
 private async deleteInputRows(tx:Connection,id:string,inputId:string){const input=(await tx.query('SELECT * FROM project_inputs WHERE id=$1 AND project_id=$2 FOR UPDATE',[inputId,id]))[0];if(!input)throw new HttpError(404,'项目资料不存在');await tx.query('DELETE FROM project_requirements WHERE project_id=$1 AND source_input_id=$2',[id,inputId]);
  // Existing proposals pin their own illustrations. Retire them from current inputs
  // without changing IDs, bytes or provenance needed to export an older snapshot.
  await tx.query(`UPDATE project_assets a SET input_id=NULL,retired_at=now() WHERE a.project_id=$1 AND a.input_id=$2 AND EXISTS(
   SELECT 1 FROM generated_documents d WHERE d.project_id=a.project_id AND (d.output_profile->>'coverLogoAssetId'=a.id OR EXISTS(
    SELECT 1 FROM document_blocks b JOIN document_sections s ON s.id=b.section_id WHERE s.document_id=d.id AND b.content->>'type'='asset' AND b.content->>'assetId'=a.id)))`,[id,inputId]);
  await tx.query('DELETE FROM project_assets WHERE project_id=$1 AND input_id=$2',[id,inputId]);await tx.query('DELETE FROM project_inputs WHERE project_id=$1 AND id=$2',[id,inputId]);if(input.document_id)await this.deletePrivateDocument(tx,id,input.document_id);}
 private async deletePrivateDocument(tx:Connection,projectId:string,documentId:string){const document=(await tx.query("SELECT id,source_document_id FROM documents WHERE id=$1 AND project_id=$2 AND scope='project'",[documentId,projectId]))[0];if(!document)throw new HttpError(409,'资料归属不符，未执行删除');for(const table of ['project_requirements'])await tx.query(`DELETE FROM ${table} WHERE source_chunk_id IN (SELECT id FROM knowledge_chunks WHERE document_id=$1)`,[documentId]);for(const table of ['classification_results','document_applications','document_topics','document_products'])await tx.query(`DELETE FROM ${table} WHERE version_id IN (SELECT id FROM document_versions WHERE document_id=$1)`,[documentId]);for(const table of ['audit_events','confirmed_examples','ingestion_jobs','refinement_proposals','refinement_applies','extracted_facts','knowledge_chunks'])await tx.query(`DELETE FROM ${table} WHERE document_id=$1`,[documentId]);await tx.query('DELETE FROM document_versions WHERE document_id=$1',[documentId]);await tx.query("DELETE FROM documents WHERE id=$1 AND project_id=$2 AND scope='project'",[documentId,projectId]);await tx.query('DELETE FROM source_documents WHERE id=$1 AND NOT EXISTS(SELECT 1 FROM documents WHERE source_document_id=$1)',[document.source_document_id]);}
 async removeInput(id:string,inputId:string){await this.row(id);const keys=await this.ownedKeys(id,inputId);await this.db.transaction(async tx=>{await this.row(id,tx,true);await this.deleteInputRows(tx,id,inputId);await this.invalidate(tx,id);await this.audit(tx,id,'input_removed',{inputId},null);});await this.cleanupKeys(id,keys);return this.rebuildContext(id);}
 async replaceInput(id:string,inputId:string,input:{filename:string;bytes:Uint8Array;mimeType?:string}){await this.downloadInput(id,inputId);return this.addInput(id,input,inputId);}
 async viewInput(id:string,inputId:string){await this.row(id);const row=(await this.db.query('SELECT * FROM project_inputs WHERE id=$1 AND project_id=$2',[inputId,id]))[0];if(!row)throw new HttpError(404,'项目资料不存在');return {input:this.inputRecord(row),text:row.parsed_document?.plainText||'',engineering:row.engineering_data||undefined};}
 async remove(id:string){await this.row(id);const keys=await this.ownedKeys(id);await this.db.transaction(async tx=>{await this.row(id,tx,true);if((await tx.query("SELECT j.id FROM generation_jobs j JOIN generated_documents d ON d.id=j.document_id WHERE d.project_id=$1 AND j.status IN ('queued','running')",[id])).length)throw new HttpError(409,'方案正在生成，请停止生成任务后删除项目');await tx.query('DELETE FROM audit_events WHERE generated_document_id IN (SELECT id FROM generated_documents WHERE project_id=$1)',[id]);await tx.query('DELETE FROM generation_jobs WHERE document_id IN (SELECT id FROM generated_documents WHERE project_id=$1)',[id]);await tx.query('DELETE FROM generated_documents WHERE project_id=$1',[id]);await tx.query('DELETE FROM project_requirements WHERE project_id=$1',[id]);for(const input of await tx.query('SELECT id FROM project_inputs WHERE project_id=$1',[id]))await this.deleteInputRows(tx,id,input.id);await tx.query('DELETE FROM project_assets WHERE project_id=$1',[id]);for(const table of ['project_facts','project_context_snapshots','project_audit_events'])await tx.query(`DELETE FROM ${table} WHERE project_id=$1`,[id]);await tx.query('DELETE FROM projects WHERE id=$1',[id]);});await this.cleanupKeys(id,keys);return {deleted:true};}
 async addAsset(id:string,input:{filename:string;buffer:Uint8Array;mimeType?:string;role?:string}){await this.row(id);const bytes=Buffer.from(input.buffer);if(!bytes.length||bytes.length>20*1024*1024)throw new HttpError(400,'图片须小于 20 MB');let mimeType='',width=0,height=0;if(bytes.length>24&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))){mimeType='image/png';if(bytes.length<45||!bytes.subarray(-12).equals(Buffer.from([0,0,0,0,73,69,78,68,174,66,96,130])))throw new HttpError(400,'PNG 图片不完整');width=bytes.readUInt32BE(16);height=bytes.readUInt32BE(20);}else if(bytes[0]===255&&bytes[1]===216){if(bytes.length<4||bytes.at(-2)!==255||bytes.at(-1)!==217)throw new HttpError(400,'JPEG 图片不完整');mimeType='image/jpeg';for(let offset=2;offset+9<bytes.length;){if(bytes[offset]!==255)break;const marker=bytes[offset+1];if(marker===0xda||marker===0xd9)break;const size=bytes.readUInt16BE(offset+2);if(size<2||offset+size+2>bytes.length)break;if([0xc0,0xc1,0xc2].includes(marker)){height=bytes.readUInt16BE(offset+5);width=bytes.readUInt16BE(offset+7);break;}offset+=size+2;}}if(!mimeType||!width||!height||width*height>64000000)throw new HttpError(400,'请上传有效 PNG 或 JPEG 图片');const inputId=randomUUID(),assetId=randomUUID(),hash=createHash('sha256').update(bytes).digest('hex'),objectKey=`projects/${id}/assets/${assetId}.${mimeType==='image/png'?'png':'jpg'}`,filename=path.basename(input.filename.replace(/\\/g,'/'));await this.knowledge.storage.put(objectKey,bytes);const sourceRef:SourceReference={type:'user',id:inputId,label:filename};await this.db.transaction(async tx=>{await this.row(id,tx,true);await tx.query("INSERT INTO project_inputs(id,project_id,kind,filename,title,content_hash,object_key,mime_type,status) VALUES($1,$2,'image',$3,$3,$4,$5,$6,'ready')",[inputId,id,filename,`${hash}:${assetId}`,objectKey,mimeType]);await tx.query('INSERT INTO project_assets(id,project_id,input_id,role,filename,mime_type,object_key,width,height,source_ref) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)',[assetId,id,inputId,input.role==='logo'?'logo':'illustration',filename,mimeType,objectKey,width,height,JSON.stringify(sourceRef)]);});return (await this.downloadAsset(id,assetId)).asset;}

 async queryChunks(projectId:string,query:string,limit=8,sourceIds?:string[]) {
  await this.row(projectId);const text=queryText(query,'or');
  const rows=await this.db.query(`SELECT c.id,c.document_id,c.version_id,c.text,d.title,i.id AS input_id,CASE WHEN $2='' THEN 0 ELSE ts_rank_cd(c.search_vector,to_tsquery('simple',$2)) END AS score
   FROM knowledge_chunks c JOIN documents d ON d.id=c.document_id JOIN project_inputs i ON i.document_id=d.id AND i.project_id=d.project_id
   WHERE d.organization_id='default' AND d.workspace_id='default' AND d.scope='project' AND d.project_id=$1 AND d.status='active' AND d.canonical_document_id IS NULL
    AND c.version_id=d.active_version_id AND i.status='ready' AND ($2='' OR c.search_vector @@ to_tsquery('simple',$2))
    AND ($4::text[] IS NULL OR c.id=ANY($4::text[]) OR d.id=ANY($4::text[]) OR i.id=ANY($4::text[]))
   ORDER BY score DESC,c.id LIMIT $3`,[projectId,text,Math.max(1,Math.min(30,limit)),sourceIds?.length?sourceIds:null]);
  const seen=new Set<string>();return rows.filter(row=>{const key=createHash('sha256').update(row.text.replace(/\s+/g,' ').trim()).digest('hex');if(seen.has(key))return false;seen.add(key);return true;}).map(row=>({id:row.id,documentId:row.document_id,versionId:row.version_id,title:row.title,text:row.text,sourceInputId:row.input_id,score:Number(row.score)}));
 }
 async downloadAsset(projectId:string,assetId:string){await this.row(projectId);const row=(await this.db.query('SELECT * FROM project_assets WHERE id=$1 AND project_id=$2',[assetId,projectId]))[0];if(!row)throw new HttpError(404,'项目图片不存在');return {asset:this.assetRecord(row),bytes:await this.knowledge.storage.get(row.object_key)};}
 async downloadInput(projectId:string,inputId:string){await this.row(projectId);const row=(await this.db.query('SELECT * FROM project_inputs WHERE id=$1 AND project_id=$2',[inputId,projectId]))[0];if(!row)throw new HttpError(404,'项目资料不存在');return {input:this.inputRecord(row),mimeType:row.mime_type||'application/octet-stream',bytes:await this.knowledge.storage.get(row.object_key)};}
 async getContext(id:string):Promise<ProjectContext>{const project=await this.row(id);const row=(await this.db.query('SELECT context,confirmed_at FROM project_context_snapshots WHERE project_id=$1 AND revision=$2',[id,project.context_revision]))[0];if(!row)throw new HttpError(409,'项目上下文尚未生成');return {...row.context,confirmed:project.confirmed_revision===project.context_revision&&row.context.inputRevision===project.input_revision,confirmedAt:row.confirmed_at?date(row.confirmed_at):undefined};}

 private async sources(id:string):Promise<RequirementSource[]>{const rows=await this.db.query("SELECT id,document_id,title,filename,parsed_document FROM project_inputs WHERE project_id=$1 AND status='ready' AND kind IN ('document','text') ORDER BY created_at,id",[id]);const result=[];for(const row of rows){const chunks=await this.db.query('SELECT c.id,c.text FROM knowledge_chunks c JOIN documents d ON d.id=c.document_id WHERE d.id=$1 AND d.project_id=$2 AND d.scope=\'project\' AND c.version_id=d.active_version_id ORDER BY c.chunk_order',[row.document_id,id]);result.push({id:row.id,title:row.title&&row.title.length>6?row.title:row.filename,text:row.parsed_document?.plainText||'',chunks:chunks as {id:string;text:string}[]});}const notes=await this.listNotes(id);for(const note of notes.filter(n=>n.status==='active'))result.push({id:note.id,title:note.title,text:note.text,chunks:[],kind:'manual_note' as const});return result;}
 private async legacyEngineering(id:string){
  const rows=await this.db.query("SELECT id,filename,object_key,engineering_data,warnings FROM project_inputs WHERE project_id=$1 AND kind='engineering' AND status='ready' ORDER BY created_at,id",[id]);
  const upgrades=[];
  for(const row of rows){if(Number(row.engineering_data?.metadata?.adapterVersion)>=2)continue;
   const parsed=await new SceneLabReportAdapter().parse(await this.knowledge.storage.get(row.object_key),id,row.id,row.filename);
   // Existing assets are immutable references used by older contexts, documents and cover logos.
   const assets=await this.db.query('SELECT * FROM project_assets WHERE project_id=$1 AND input_id=$2 ORDER BY id',[id,row.id]);parsed.engineering.assets=assets.map(asset=>this.assetRecord(asset));
   upgrades.push({id:row.id,previous:row.engineering_data,engineering:parsed.engineering,warnings:[...new Set([...(row.warnings||[]),...parsed.warnings])]});
  }return upgrades;
 }
 async rebuildContext(id:string,options:{useAI?:boolean;resetRequirementId?:string;restoreCategories?:string[]}&RequirementExtractionOptions={}):Promise<ProjectContext> {
  const project=await this.row(id),sources=await this.sources(id),upgrades=await this.legacyEngineering(id);let requirements=parseRequirements(sources);
  if(options.useAI){if(!sources.length)throw new HttpError(400,'请先导入客户需求资料');const config=await this.knowledge.settings.config();if(!config||!this.providerFactory)throw new HttpError(400,'请先配置模型');
   const model=options.model||'kimi-k3';let host='';try{const url=new URL(config.baseUrl);if(url.protocol==='https:')host=url.hostname;}catch{/* rejected below */}
   if(host!=='api.moonshot.cn'||!['kimi-k3','kimi-k2.6'].includes(model))throw new HttpError(400,'项目需求提取当前支持 Moonshot.cn 的 kimi-k3、kimi-k2.6');
   const profile=modelProfile(model),limitsEnabled=options.limitsEnabled===true,requests=buildRequirementRequests(sources,{limitsEnabled,model}),maxTokens=limitsEnabled?4000:profile.defaultOutputTokens;
   const inputBytes=requests.reduce((sum,item)=>sum+item.inputBytes,0),reservation=requests.reduce((sum,item)=>sum+estimatedModelCost(model,item.inputBytes+1024,maxTokens)*3,0),requestId=randomUUID();
   // Keep the shared usage ledger even when the optional application budget is disabled.
   await this.db.transaction(async tx=>{await this.row(id,tx,true);await tx.query("INSERT INTO settings(key,value) VALUES('projectExtractionBudget','{\"reservedCny\":0}'::jsonb) ON CONFLICT DO NOTHING");const budget=(await tx.query("SELECT value FROM settings WHERE key='projectExtractionBudget' FOR UPDATE"))[0].value;const prior=Number(budget.reservedCny)||0;if(limitsEnabled&&prior+reservation>25)throw new HttpError(409,'项目需求提取累计预算已达到 25 元上限；可关闭额度限制后继续');await tx.query("UPDATE settings SET value=$1::jsonb,updated_at=now() WHERE key='projectExtractionBudget'",[JSON.stringify({reservedCny:prior+reservation})]);await this.audit(tx,id,'requirement_extraction_reserved',{reservedCny:prior},{requestId,inputBytes,maxOutputTokens:maxTokens,reservedCny:reservation,totalReservedCny:prior+reservation,model,retryAllowance:3,limitsEnabled,batchCount:requests.length});});
   // Extraction runs only on an explicit request. Failures retain reservations and the previous context.
   try{requirements=await extractRequirementsAI(sources,this.providerFactory({...config,model,temperature:profile.temperature,maxTokens,requestTimeoutMs:profile.requestTimeoutMs,reasoningEffort:model==='kimi-k3'?'max':undefined}),async(response,bytes)=>{await this.audit(this.db,id,'requirement_extraction_usage',null,{requestId,inputBytes:bytes,model,usage:response.usage||null});},{limitsEnabled,model});}catch{throw new HttpError(502,'需求提取未完成，原项目事实未改动；用量预留已保留以覆盖可能已发生的请求');}
  }
  return this.db.transaction(async tx=>{
   const current=await this.row(id,tx,true);if(current.context_revision!==project.context_revision||current.input_revision!==project.input_revision)throw new HttpError(409,'项目资料已变化，请重新提取');
   for(const upgrade of upgrades){const updated=await tx.query('UPDATE project_inputs SET engineering_data=$3::jsonb,warnings=$4::jsonb WHERE id=$1 AND project_id=$2 AND engineering_data=$5::jsonb RETURNING id',[upgrade.id,id,JSON.stringify(upgrade.engineering),JSON.stringify(upgrade.warnings),JSON.stringify(upgrade.previous)]);if(!updated.length)throw new HttpError(409,'工程报告适配结果已更新，请重新提取');await this.audit(tx,id,'engineering_adapter_upgraded',{inputId:upgrade.id,adapterVersion:upgrade.previous?.metadata?.adapterVersion??1},{inputId:upgrade.id,adapterVersion:2});}
   const previous=(await tx.query('SELECT context FROM project_context_snapshots WHERE project_id=$1 AND revision=$2',[id,current.context_revision]))[0]?.context as ProjectContext|undefined;
   const retainedAI=(previous?.aiRequirementItems||[]).filter(({item})=>sources.some(s=>s.id===item.sourceInputId&&s.text.includes(item.evidence)));
   const aiItems=options.useAI?(requirements.extractedItems||[]):retainedAI;
   const aiReviewedSourceIds=options.useAI?(requirements.aiReviewedSourceIds||[]):(previous?.aiReviewedSourceIds||[]).filter(sourceId=>sources.some(s=>s.id===sourceId));
   const extractedFacts=requirements.extractedFacts,extractedFingerprint=requirements.extractedFingerprint;
   if(!options.useAI&&aiReviewedSourceIds.length){requirements=parseRequirements(sources.filter(s=>!aiReviewedSourceIds.includes(s.id)));}
   // Explicit user corrections survive another import or extraction.
   if(previous?.reviewedInputIds?.length){
    const reviewed=new Set(previous.reviewedInputIds);
    for(const key of ['goals','interfaces','protocols','environment','installationConstraints','specialRequirements','acceptanceCriteria'] as const)requirements[key]=requirements[key].filter(item=>!reviewed.has(item.sourceInputId));
    for(const [key,item] of Object.entries(requirements.performance))if(item&&reviewed.has(item.sourceInputId))delete requirements.performance[key as keyof ProjectRequirements['performance']];
   }
   if(previous)for(const [category,item] of requirementEntries(previous.requirements).filter(([,item])=>item.confirmedByUser&&item.id!==options.resetRequirementId)){
    if(category.startsWith('performance.'))requirements.performance[category.slice(12) as keyof ProjectRequirements['performance']]=item;
    else {const key=category as 'goals';requirements[key]=requirements[key].filter(existing=>existing.id!==item.id);requirements[key].push(item);}
   }
   requirements.projectName=current.name;requirements.customerName=current.customer_name||undefined;requirements.unresolved=requirementQuestions(requirements);
   const input=(await tx.query("SELECT engineering_data FROM project_inputs WHERE project_id=$1 AND kind='engineering' AND status='ready' ORDER BY created_at DESC,id DESC LIMIT 1",[id]))[0];
   const engineering=input?.engineering_data as EngineeringData|undefined;
   const context:ProjectContext={projectId:id,revision:current.context_revision+1,inputRevision:current.input_revision,confirmed:false,summary:current.description||`${current.name}${current.customer_name?`；客户：${current.customer_name}`:''}`,requirements,engineering,lockedFacts:[],products:engineering?.deployment?.models?.map(model=>model.name)||[],capabilities:[],assets:engineering?.assets||[],conflicts:[],unresolved:requirements.unresolved};
   context.reviewedInputIds=previous?.reviewedInputIds;
   const decisions=(await tx.query('SELECT decision FROM project_requirement_decisions WHERE project_id=$1',[id])).map(r=>r.decision as WorkspaceRequirement);
   context.aiRequirementItems=aiItems;context.aiReviewedSourceIds=aiReviewedSourceIds;
   context.workspaceRequirements=mergeWorkspaceRequirements(id,sources,requirements,previous?.workspaceRequirements?.filter(r=>r.id!==options.resetRequirementId),decisions,previous?.reviewedInputIds,options.restoreCategories,aiItems,aiReviewedSourceIds);
   context.requirements=safeRequirements(requirements,context.workspaceRequirements);
   context.requirements.unresolved=requirementQuestions(context.requirements);
   context.fingerprint=inferFingerprint([current.description,...sources.map(s=>s.text)].join('\n'),context.products,{...(options.useAI?Object.fromEntries(['applications','targetObjects','scenarios','topics','modules','products','environment','constraints'].map(k=>[k,[]])):previous?.aiReviewedSourceIds?.length?previous.fingerprint:undefined),...extractedFingerprint,...current.fingerprint});
   context.factProposals=[...factProposals(sources.filter(s=>!aiReviewedSourceIds.includes(s.id))),...(extractedFacts||previous?.factProposals||[]).filter(f=>f.evidenceRefs.some(e=>sources.some(s=>s.id===e.sourceId&&s.text.includes(e.excerpt||'')))).map(f=>({...f,key:userFactKey(f.label,f.category,f.value)}))];
   context.factProposals=mergeFactProposals(context.factProposals);
   const userFacts=await tx.query("SELECT * FROM project_facts WHERE project_id=$1 AND source_type='user'",[id]);context.lockedFacts=userFacts.map(row=>({id:row.id,key:row.key,label:row.label,value:row.value,unit:row.unit||undefined,sourceType:'user',sourceRef:{...row.source_ref,evidenceRefs:row.source_ref?.evidenceRefs?.filter((e:any)=>e.sourceType==='user'||sources.some(s=>s.id===e.sourceId))},evidenceRefs:row.source_ref?.evidenceRefs?.filter((e:any)=>e.sourceType==='user'||sources.some(s=>s.id===e.sourceId)),locked:true}));
   const selectedProducts=context.lockedFacts.find(fact=>fact.key==='products');if(selectedProducts&&Array.isArray(selectedProducts.value))context.products=selectedProducts.value as string[];
   if(context.fingerprint)context.fingerprint=normalizeFingerprint({...context.fingerprint,products:[...new Set([...context.fingerprint.products,...context.products])]},await tx.query<TagAlias>('SELECT dimension,alias,canonical FROM knowledge_tag_aliases'));
   const userSummary=context.lockedFacts.find(fact=>fact.key==='project.summary');if(userSummary&&typeof userSummary.value==='string')context.summary=userSummary.value;
   await this.derive(context,tx);return this.persistContext(tx,current,context,'context_rebuilt');
  });
 }

 private async derive(context:ProjectContext,tx:Connection) {
  const user=context.lockedFacts.filter(fact=>fact.sourceType==='user');const facts:LockedFact[]=[];const conflicts:ProjectConflict[]=[];
  const add=(key:string,label:string,value:unknown,unit:string|undefined,sourceType:LockedFact['sourceType'],sourceRef:SourceReference)=>{if(value!==undefined&&value!==null)facts.push({id:stableId(context.projectId,sourceType,key),key,label,value,unit,sourceType,sourceRef,locked:true});};
  for(const [category,item] of requirementEntries(context.requirements))add(`requirement.${category}.${item.id}`,requirementCategoryLabels[category]||'客户要求',item.value,undefined,'customer_requirement',{type:item.sourceInputId==='user'?'user':'project_input',id:item.sourceInputId,label:requirementCategoryLabels[category]||'客户要求',evidence:item.evidence});
  const engineering=context.engineering;context.capabilities=[];
  if(engineering){const ref=engineering.sourceRef;add('scene.boundaryM','场地尺寸',engineering.scene?.boundaryM,'m','engineering_data',ref);add('deployment.equipmentCount','相机数量',engineering.deployment?.equipmentCount,'台','engineering_data',ref);add('deployment.models','相机型号与数量',engineering.deployment?.models,undefined,'engineering_data',ref);
   if(engineering.deployment?.opticalConfigurations?.length)add('engineering.opticalConfigurations','原报告工程仿真光学配置',engineering.deployment.opticalConfigurations,undefined,'engineering_data',ref);
   const labels:Record<string,string>={coverageGe1:'至少1视点覆盖率',coverageGe2:'至少2视点覆盖率',coverageGe3:'至少3视点覆盖率',coverageGe4:'至少4视点覆盖率',coverageGe5:'至少5视点覆盖率',averageViewCount:'平均可见视点数',meanErrorMm:'平均理论定位误差',p90ErrorMm:'P90理论定位误差',p95ErrorMm:'P95理论定位误差',under03Mm:'理论误差≤0.3mm比例',under05Mm:'理论误差≤0.5mm比例'};
   for(const [key,value] of Object.entries(engineering.performance||{})){const unit=key.startsWith('coverage')||key.startsWith('under')?'%':key.endsWith('Mm')?'mm':undefined;add(`performance.${key}`,labels[key]||key,value,unit,'engineering_data',ref);if(value!==null&&value!==undefined)context.capabilities.push({key,label:labels[key]||key,value,unit,sourceRef:ref});}
   const accuracy=context.requirements.performance.accuracy;const actual=engineering.performance?.p95ErrorMm;
   if(accuracy&&actual!=null){const text=typeof accuracy.value==='string'?accuracy.value:String(accuracy.value);const match=text.match(/(?:≤|<=|不超过|不大于|小于等于|小于|低于|<)\s*(\d+(?:\.\d+)?)\s*(mm|毫米|cm|厘米|m|米)?/i);if(match){const limit=Number(match[1])*(/^(?:cm|厘米)$/i.test(match[2]||'')?10:/^(?:m|米)$/i.test(match[2]||'')?1000:1);if(actual>limit)conflicts.push({id:stableId(context.projectId,'accuracy',String(limit),String(actual)),key:'accuracy',severity:'error',message:`客户要求 ${text}；工程 P95 理论误差为 ${actual} mm。两者存在差异，且须确认指标口径，不能声明已满足要求。`,requirement:accuracy,actual,sourceRefs:[{type:'project_input',id:accuracy.sourceInputId,label:'客户精度要求',evidence:accuracy.evidence},ref],status:'open'});}}
  }
  // User facts take precedence only for the same fact key; customer targets remain separate from capabilities.
  if(engineering)for(const fact of user){const [group,key]=fact.key.split('.');const original=(engineering as any)[group]?.[key];if(original!==undefined&&JSON.stringify(original)!==JSON.stringify(fact.value))conflicts.push({id:stableId(context.projectId,'engineering-override',fact.key),key:fact.key,severity:'warning',message:`用户确认的${fact.label}与原工程报告不同。正文采用用户确认值，工程图片仍来自原报告，请核对或更新工程报告。`,actual:original,sourceRefs:[fact.sourceRef,engineering.sourceRef],status:'open'});}
  context.lockedFacts=[...facts.filter(fact=>!user.some(prior=>prior.key===fact.key)),...user];context.conflicts=conflicts;
  if(engineering?.deployment?.opticalConfigurations?.length){
   // Reuse exact, active authoritative product retrieval on this transaction connection.
   const structured=new StructuredService({...this.db,query:tx.query.bind(tx)});
   context.conflicts.push(...engineeringOpticsConflicts(context,await structured.productFacts(context.products)));
  }
  const answers=await tx.query('SELECT question_id,answer FROM project_clarification_answers WHERE project_id=$1',[context.projectId]);
  context.requirements.unresolved=context.requirements.unresolved.map(q=>{const answer=answers.find(a=>a.question_id===q.id)?.answer;return answer?{...q,answerMode:answer.mode,answer:answer.value,resolved:answer.mode!=='unknown'}:q;});
  if(context.lockedFacts.some(f=>f.key==='deployment.equipmentCount'))context.requirements.unresolved=context.requirements.unresolved.filter(q=>q.key!=='cameraCount');
  for(const row of context.workspaceRequirements||[])if(row.status==='conflicted')context.conflicts.push({id:row.id,key:row.semanticKey,severity:'error',message:`${row.label}存在不同来源的值，请选择采用值。`,sourceRefs:row.evidenceRefs.map(e=>({type:e.sourceType==='user'?'user' as const:'project_input' as const,id:e.sourceId,label:row.label,evidence:e.excerpt})),status:'open'});
  context.unresolved=context.requirements.unresolved.filter(question=>!question.resolved);
 }
 private async persistContext(tx:Connection,project:any,context:ProjectContext,action:string) {
  await tx.query('INSERT INTO project_context_snapshots(id,project_id,revision,context) VALUES($1,$2,$3,$4::jsonb)',[randomUUID(),project.id,context.revision,JSON.stringify(context)]);
  await tx.query("UPDATE projects SET context_revision=$2,confirmed_revision=NULL,status=CASE WHEN status='archived' THEN status ELSE 'draft' END,updated_at=now() WHERE id=$1",[project.id,context.revision]);
  await tx.query("DELETE FROM project_facts WHERE project_id=$1 AND source_type<>'user'",[project.id]);
  for(const fact of context.lockedFacts)await tx.query('INSERT INTO project_facts(id,project_id,key,label,value,unit,source_type,source_ref,locked) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8::jsonb,true) ON CONFLICT(project_id,key,source_type) DO UPDATE SET label=excluded.label,value=excluded.value,unit=excluded.unit,source_ref=excluded.source_ref,updated_at=now()',[fact.id,project.id,fact.key,fact.label,JSON.stringify(fact.value),fact.unit||null,fact.sourceType,JSON.stringify(fact.sourceRef)]);
  await tx.query('DELETE FROM project_requirements WHERE project_id=$1',[project.id]);
  for(const [category,item] of requirementEntries(context.requirements))await tx.query('INSERT INTO project_requirements(id,project_id,category,source_input_id,source_chunk_id,item) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(id) DO UPDATE SET category=excluded.category,item=excluded.item,updated_at=now()',[item.id,project.id,category,item.sourceInputId==='user'||!(await tx.query('SELECT id FROM project_inputs WHERE id=$1 AND project_id=$2',[item.sourceInputId,project.id])).length?null:item.sourceInputId,item.sourceChunkId||null,JSON.stringify(item)]);
  await this.audit(tx,project.id,action,{revision:project.context_revision},{revision:context.revision});return context;
 }
 async patchContext(id:string,input:ContextPatch):Promise<ProjectContext> {
  for(const fact of input.facts??[]){
   if(fact.value===undefined||JSON.stringify(fact.value).length>10000)throw new HttpError(400,'项目事实为空或过长');
   if(fact.key==='scene.boundaryM'&&(!Array.isArray(fact.value)||fact.value.length!==3||fact.value.some(v=>typeof v!=='number'||!Number.isFinite(v)||v<=0)||fact.unit&&fact.unit!=='m'))throw new HttpError(400,'场地尺寸须为三个正数，单位 m');
   if(fact.key==='deployment.equipmentCount'&&(!Number.isInteger(fact.value)||Number(fact.value)<0||Number(fact.value)>10000||fact.unit&&fact.unit!=='台'))throw new HttpError(400,'设备数量须为 0–10000 的整数，单位台');
   if(fact.key==='deployment.models'&&(!Array.isArray(fact.value)||fact.value.length>100||fact.value.some(v=>!v||typeof v.name!=='string'||!v.name.trim()||!Number.isInteger(v.count)||v.count<0)))throw new HttpError(400,'设备型号需填写 [{"name":"K18","count":16}] 形式的配置');
   if(fact.key.startsWith('performance.')&&(typeof fact.value!=='number'||!Number.isFinite(fact.value)||fact.value<0||/coverage|under/.test(fact.key)&&fact.value>100))throw new HttpError(400,'性能事实须为有效非负数，百分比为 0–100');
  }
  return this.db.transaction(async tx=>{const project=await this.row(id,tx,true);if(project.context_revision!==input.revision)throw new HttpError(409,'项目理解已更新，请刷新后编辑');const stored=(await tx.query('SELECT context FROM project_context_snapshots WHERE project_id=$1 AND revision=$2',[id,input.revision]))[0];if(!stored)throw new HttpError(409,'项目上下文不存在');const context=structuredClone(stored.context) as ProjectContext;
   if(context.inputRevision!==project.input_revision)throw new HttpError(409,'存在新导入资料，请重新提取项目理解');
   context.revision++;context.confirmed=false;delete context.confirmedAt;if(input.summary!==undefined){context.summary=input.summary;context.lockedFacts=context.lockedFacts.filter(fact=>!(fact.key==='project.summary'&&fact.sourceType==='user'));context.lockedFacts.push({id:stableId(id,'user','project.summary'),key:'project.summary',label:'项目概述',value:input.summary,sourceType:'user',sourceRef:{type:'user',id,label:'用户确认项目概述',evidence:input.summary},locked:true});}
   if(input.requirements){context.reviewedInputIds=(await tx.query('SELECT id FROM project_inputs WHERE project_id=$1',[id])).map(r=>r.id);const old=new Map(requirementEntries(context.requirements).map(([,item])=>[item.id,item]));context.requirements=input.requirements;for(const [category,item] of requirementEntries(context.requirements)){const original=old.get(item.id);if(!original||JSON.stringify(original.value)!==JSON.stringify(item.value)){item.id=stableId(id,'user-requirement',category,JSON.stringify(item.value));item.sourceInputId='user';delete item.sourceChunkId;item.evidence=`人工确认：${typeof item.value==='string'?item.value:JSON.stringify(item.value)}`;}else{item.sourceInputId=original.sourceInputId;item.sourceChunkId=original.sourceChunkId;item.evidence=original.evidence;}item.confirmedByUser=true;item.confidence=1;}}
   if(input.requirements){
    const canonical:WorkspaceRequirement[]=[];
    for(const [category,item] of requirementEntries(context.requirements)){
     const semanticKey=category.startsWith('performance.')?category:`${category}:${normalizedRequirement(item.value)}`;
     const prior=context.workspaceRequirements?.find(r=>r.id===item.id||r.semanticKey===semanticKey);
     const row:WorkspaceRequirement={id:stableId(id,'requirement',semanticKey),semanticKey,category,label:prior?.label||requirementCategoryLabels[category]||'客户要求',value:item.value,status:'confirmed',confirmedByUser:true,evidenceRefs:[...(prior?.evidenceRefs||[]),{sourceType:'user',sourceId:id,excerpt:item.evidence}]};
     await tx.query('INSERT INTO project_requirement_decisions(id,project_id,semantic_key,decision) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(project_id,semantic_key) DO UPDATE SET decision=excluded.decision,updated_at=now()',[row.id,id,semanticKey,JSON.stringify(row)]);canonical.push(row);
    }
    context.workspaceRequirements=canonical;
   }
   for(const item of input.facts||[]) {const original=context.lockedFacts.find(f=>f.key===item.key&&f.sourceType==='user'&&JSON.stringify(f.value)===JSON.stringify(item.value));const evidenceRefs=[...(original?.evidenceRefs||[]),...(item.evidenceRefs||[]),{sourceType:'user' as const,sourceId:id,excerpt:`人工确认：${item.label}：${JSON.stringify(item.value)}`}];const unique=[...new Map(evidenceRefs.map(e=>[`${e.sourceType}:${e.sourceId}:${e.excerpt}`,e])).values()];const fact:LockedFact={...item,evidenceRefs:unique,id:stableId(id,'user',item.key),sourceType:'user',sourceRef:{type:'user',id,label:'用户确认项目事实',evidence:`${item.label}：${JSON.stringify(item.value)}`,evidenceRefs:unique},locked:true};context.lockedFacts=context.lockedFacts.filter(old=>!(old.key===item.key&&old.sourceType==='user'));context.lockedFacts.push(fact);}
   if(input.products){context.products=[...new Set(input.products)];context.lockedFacts=context.lockedFacts.filter(fact=>!(fact.key==='products'&&fact.sourceType==='user'));context.lockedFacts.push({id:stableId(id,'user','products'),key:'products',label:'人工选择产品型号',value:context.products,sourceType:'user',sourceRef:{type:'user',id,label:'用户选择型号',evidence:context.products.join('、')},locked:true});}
   const previousQuestions=new Map(context.requirements.unresolved.map(q=>[q.id,q]));context.requirements.unresolved=requirementQuestions(context.requirements).map(q=>({...q,resolved:previousQuestions.get(q.id)?.resolved||input.resolvedQuestionIds?.includes(q.id)||false}));await this.derive(context,tx);return this.persistContext(tx,project,context,'context_edited');});
 }
 async applyReconstructionReview(id:string,input:ReconstructionReview):Promise<ProjectContext> {
  return this.db.transaction(async tx=>{
   const project=await this.row(id,tx,true);if(input.scope!=='historical_reconstruction_only'||!isHistoricalReconstructionProject(project.description))throw new HttpError(409,'仅带明确历史复建回归标记的项目可接收此资料复核，普通客户项目不可使用');
   if(project.context_revision!==input.revision)throw new HttpError(409,'项目资料已更新，请重新核对复核版本');
   const current=(await tx.query('SELECT context FROM project_context_snapshots WHERE project_id=$1 AND revision=$2',[id,input.revision]))[0]?.context as ProjectContext|undefined;if(!current||current.inputRevision!==project.input_revision)throw new HttpError(409,'项目输入尚未完成解析，请先完成资料分析');
   const owned=await tx.query("SELECT i.*,v.id AS version_id FROM project_inputs i LEFT JOIN document_versions v ON v.document_id=i.document_id WHERE i.project_id=$1 AND i.status='ready' AND i.kind IN ('document','text')",[id]);
   const normalize=(text:string)=>text.replace(/\s+/g,' ').trim();
   const evidence=async(ref:ReconstructionReview['facts'][number]['evidence'])=>{
    const source=owned.find(r=>r.id===ref.projectInputId);if(!source||!ref.excerpt.trim()||!normalize(source.parsed_document?.plainText||'').includes(normalize(ref.excerpt)))throw new HttpError(400,'复核依据不属于当前项目资料，或原文摘录不匹配');
    const original=(await tx.query('SELECT parsed_document,content_hash FROM document_versions WHERE id=$1 AND document_id=$2',[ref.sourceVersionId,ref.sourceDocumentId]))[0];const block=original?.parsed_document?.blocks?.[ref.sourceBlockIndex];if(!block||original.content_hash!==source.content_hash||!normalize(block.text||'').includes(normalize(ref.excerpt)))throw new HttpError(400,'复核依据的原文版本或段落位置不匹配');
    return {sourceType:'project_file' as const,sourceId:source.id,excerpt:ref.excerpt,sourceDocumentId:ref.sourceDocumentId,sourceVersionId:ref.sourceVersionId,sourceBlockIndex:ref.sourceBlockIndex,headingPath:ref.headingPath};
   };
   const workspace:WorkspaceRequirement[]=[],facts:LockedFact[]=[];
   for(const requirement of input.requirements){if(!requirementCategoryLabels[requirement.category])throw new HttpError(400,'客户要求分类无效');const refs=[];for(const ref of [requirement.evidence,...(requirement.additionalEvidence||[])])refs.push(await evidence(ref));const semanticKey=requirement.category.startsWith('performance.')?requirement.category:`${requirement.category}:${normalizedRequirement(requirement.value,requirement.unit)}`;if(workspace.some(r=>r.semanticKey===semanticKey))throw new HttpError(400,'复核要求包含重复口径，请在复核清单中先合并');workspace.push({id:stableId(id,'requirement',semanticKey),semanticKey,category:requirement.category,label:requirement.label,value:requirement.value,unit:requirement.unit,status:'proposed',confirmedByUser:false,evidenceRefs:refs});}
   for(const fact of input.facts){if(facts.some(f=>f.key===fact.key)||['engineering.opticsSource','project.summary','products'].includes(fact.key))throw new HttpError(400,'历史复建事实键重复或试图覆盖内部确认字段');if(fact.value===undefined||JSON.stringify(fact.value).length>10000)throw new HttpError(400,'复核事实为空或过长');const refs=[];for(const ref of [fact.evidence,...(fact.additionalEvidence||[])])refs.push(await evidence(ref));facts.push({id:stableId(id,'historical-review',fact.key),key:fact.key,label:fact.label,value:fact.value,unit:fact.unit,sourceType:'historical_reconstruction',sourceRef:{type:'project_input',id:refs[0].sourceId,label:fact.label,evidence:refs.map(r=>r.excerpt).join('\n'),versionId:refs[0].sourceVersionId,authority:'reference'},locked:true,confirmedByUser:false,reviewScope:'historical_reconstruction_only',evidenceRefs:refs});}
   const text=owned.map(r=>r.parsed_document?.plainText||'').join('\n').toLowerCase();if(input.products.some(p=>!text.includes(p.toLowerCase())))throw new HttpError(400,'复建产品型号未在项目原文中出现');
   const requirements=safeRequirements({goals:[],performance:{},interfaces:[],protocols:[],environment:[],installationConstraints:[],specialRequirements:[],acceptanceCriteria:[],unresolved:[],projectName:project.name,customerName:project.customer_name},workspace);requirements.unresolved=requirementQuestions(requirements);
   const reviewedAt=new Date().toISOString();const context:ProjectContext={...current,revision:project.context_revision+1,confirmed:true,confirmedAt:reviewedAt,reviewScope:'historical_reconstruction_only',reviewedAt,reviewedBy:input.reviewedBy,summary:input.summary,products:input.products,fingerprint:normalizeFingerprint(input.fingerprint,await tx.query<TagAlias>('SELECT dimension,alias,canonical FROM knowledge_tag_aliases')),workspaceRequirements:workspace,requirements,lockedFacts:facts,conflicts:[],unresolved:requirements.unresolved,factProposals:[],reviewedInputIds:[],aiReviewedSourceIds:owned.map(r=>r.id),aiRequirementItems:requirementEntries(requirements).map(([category,item])=>({category,item})),doNotClaim:input.doNotClaim};
   await tx.query('DELETE FROM project_requirement_decisions WHERE project_id=$1',[id]);await tx.query('DELETE FROM project_clarification_answers WHERE project_id=$1',[id]);await tx.query('DELETE FROM project_facts WHERE project_id=$1',[id]);await tx.query('UPDATE projects SET fingerprint=$2::jsonb WHERE id=$1',[id,JSON.stringify(input.fingerprint)]);
   await this.persistContext(tx,project,context,'historical_reconstruction_review');await tx.query('UPDATE project_context_snapshots SET confirmed_at=$3 WHERE project_id=$1 AND revision=$2',[id,context.revision,reviewedAt]);await tx.query("UPDATE projects SET confirmed_revision=$2,status='context_ready' WHERE id=$1",[id,context.revision]);await this.audit(tx,id,'historical_reconstruction_ready',null,{scope:input.scope,reviewedBy:input.reviewedBy,requirements:workspace.length,facts:facts.length,newCustomerApproval:false});return context;
  });
 }
 async confirmContext(id:string,revision:number):Promise<ProjectContext> {
  await this.db.transaction(async tx=>{const project=await this.row(id,tx,true);if(project.status==='archived')throw new HttpError(409,'项目已归档');if(project.context_revision!==revision)throw new HttpError(409,'项目资料已更新，请复核最新版本');const row=(await tx.query('SELECT context FROM project_context_snapshots WHERE project_id=$1 AND revision=$2 FOR UPDATE',[id,revision]))[0];if(!row)throw new HttpError(409,'项目上下文不存在');const context=row.context as ProjectContext;
   if(context.inputRevision!==project.input_revision)throw new HttpError(409,'存在新导入资料，请重新提取后确认');
   if(!context.requirements.goals.length&&!requirementEntries(context.requirements).length&&!context.engineering&&!context.lockedFacts.some(f=>f.sourceType==='user')&&!project.description)throw new HttpError(400,'请先补充项目说明、客户资料或项目事实');
   if(context.workspaceRequirements?.some(r=>r.status==='conflicted'))throw new HttpError(409,'请先处理客户要求中的来源冲突，或选择暂不确定');
   for(const requirement of context.workspaceRequirements||[])if(requirement.status==='proposed'){requirement.status='confirmed';requirement.confirmedByUser=true;}
   context.confirmed=true;context.confirmedAt=new Date().toISOString();for(const [,item] of requirementEntries(context.requirements))item.confirmedByUser=true;
   context.reviewedInputIds=(await tx.query('SELECT id FROM project_inputs WHERE project_id=$1',[id])).map(r=>r.id);
   await tx.query('UPDATE project_context_snapshots SET context=$3::jsonb,confirmed_at=now() WHERE project_id=$1 AND revision=$2',[id,revision,JSON.stringify(context)]);await tx.query("UPDATE projects SET confirmed_revision=$2,status='context_ready',updated_at=now() WHERE id=$1",[id,revision]);await this.audit(tx,id,'context_confirmed',null,{revision,openConflicts:context.conflicts.length,unresolved:context.unresolved.length});
  });return this.getContext(id);
 }
}
