export interface SourceReference { type:'project_input'|'engineering_data'|'structured_fact'|'knowledge_chunk'|'knowledge_section'|'user'; id:string; label:string; evidence?:string; versionId?:string; authority?:string;evidenceRefs?:EvidenceRef[] }
export interface RequirementItem { id:string; key?:string; value:unknown; sourceInputId:string; sourceChunkId?:string; evidence:string; confidence:number; confirmedByUser:boolean }
export interface RequirementQuestion { id:string; key:string; question:string; sourceInputId?:string; resolved?:boolean; target?:string; answerMode?:'answer'|'unknown'|'not_applicable'|'conventional'; answer?:string }
export interface EvidenceRef {sourceType:'project_file'|'manual_note'|'user'|'scenelab';sourceId:string;excerpt?:string;sourceDocumentId?:string;sourceVersionId?:string;sourceBlockIndex?:number;headingPath?:string[]}
export interface WorkspaceRequirement {id:string;semanticKey:string;category:string;label:string;value:unknown;unit?:string;status:'proposed'|'confirmed'|'conflicted'|'unknown'|'not_applicable';evidenceRefs:EvidenceRef[];confirmedByUser:boolean;alternatives?:{value:unknown;unit?:string;evidenceRefs:EvidenceRef[]}[]}
export interface ManualRequirementNote {id:string;projectId:string;title:string;text:string;status:'active'|'archived';createdAt:string;updatedAt:string}
export interface ProjectFingerprint {applications:string[];targetObjects:string[];scenarios:string[];topics:string[];modules:string[];products:string[];environment:string[];constraints:string[]}
export interface ProjectFactProposal {id:string;key:string;label:string;value:unknown;unit?:string;category:string;evidenceRefs:EvidenceRef[]}
export interface ProjectRequirements {
 extractedFacts?:ProjectFactProposal[];extractedFingerprint?:Partial<ProjectFingerprint>;extractedItems?:{category:string;item:RequirementItem}[];aiReviewedSourceIds?:string[];
 projectName?:string; customerName?:string; application?:string; goals:RequirementItem[];
 performance:{accuracy?:RequirementItem;frameRate?:RequirementItem;latency?:RequirementItem;coverage?:RequirementItem;range?:RequirementItem;cameraCount?:RequirementItem};
 interfaces:RequirementItem[];protocols:RequirementItem[];environment:RequirementItem[];installationConstraints:RequirementItem[];specialRequirements:RequirementItem[];acceptanceCriteria:RequirementItem[];unresolved:RequirementQuestion[];
}
export interface ProjectAsset { id:string;projectId:string;inputId:string|null;retiredAt?:string;role:string;filename:string;mimeType:string;objectKey:string;width?:number;height?:number;caption?:string;sourceRef:SourceReference;url:string }
export interface EngineeringOpticalConfiguration { model:string;variant?:string;lens?:{focalLengthMm?:number|null;apertureF?:number|null};hfovDeg?:number|null;vfovDeg?:number|null;maxWorkingDistanceM?:number|null;rangeMode?:string;cameraIds:string[];sourceRef:SourceReference }
export interface EngineeringData {
 sourceType:string;scene?:{boundaryM?:[number,number,number]};deployment?:{equipmentCount?:number;models?:{name:string;count:number}[];opticalConfigurations?:EngineeringOpticalConfiguration[]};
 performance?:{coverageGe1?:number;coverageGe2?:number;coverageGe3?:number;coverageGe4?:number;coverageGe5?:number;averageViewCount?:number;meanErrorMm?:number|null;p90ErrorMm?:number|null;p95ErrorMm?:number|null;under03Mm?:number;under05Mm?:number};
 assets:ProjectAsset[];sourceRef:SourceReference;metadata?:{adapterVersion?:number;schemeId?:string;schemeRevision?:number;generatedAt?:string;accuracyMetric?:string;coverageUnit?:string};
}
export interface LockedFact { id:string;key:string;label:string;value:unknown;unit?:string;sourceType:'customer_requirement'|'engineering_data'|'structured_fact'|'user'|'historical_reconstruction';sourceRef:SourceReference;locked:true;reviewScope?:'historical_reconstruction_only';confirmedByUser?:boolean;evidenceRefs?:EvidenceRef[] }
export interface ProjectCapability { key:string;label:string;value:unknown;unit?:string;sourceRef:SourceReference }
export interface ProjectConflict { id:string;key:string;severity:'warning'|'error';message:string;requirement?:RequirementItem;actual?:unknown;sourceRefs:SourceReference[];status:'open'|'resolved' }
export interface ProjectContext { reviewScope?:'historical_reconstruction_only';reviewedAt?:string;reviewedBy?:string;doNotClaim?:string[];aiRequirementItems?:{category:string;item:RequirementItem}[];aiReviewedSourceIds?:string[];workspaceRequirements?:WorkspaceRequirement[];fingerprint?:ProjectFingerprint;factProposals?:ProjectFactProposal[];projectId:string;revision:number;inputRevision?:number;reviewedInputIds?:string[];confirmed:boolean;confirmedAt?:string;summary:string;requirements:ProjectRequirements;engineering?:EngineeringData;lockedFacts:LockedFact[];products:string[];capabilities:ProjectCapability[];assets:ProjectAsset[];conflicts:ProjectConflict[];unresolved:RequirementQuestion[] }
export interface ProjectInput { id:string;projectId:string;documentId?:string;kind:'document'|'text'|'engineering'|'image';filename:string;title:string;status:'ready'|'failed';createdAt:string;warnings:string[];error?:string }
export interface Project { id:string;organizationId:string;workspaceId:string;name:string;customerName?:string;description:string;companyName:string;documentType:string;status:'draft'|'parsing'|'context_ready'|'generating'|'generated'|'validated'|'archived';contextRevision:number;confirmedRevision:number|null;createdAt:string;updatedAt:string;inputs:ProjectInput[];assets:ProjectAsset[] }
export interface ContextPatch { revision:number;summary?:string;requirements?:ProjectRequirements;products?:string[];facts?:{key:string;label:string;value:unknown;unit?:string;evidenceRefs?:EvidenceRef[]}[];resolvedQuestionIds?:string[] }
