import { afterAll,beforeAll,describe,expect,test } from 'vitest';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { openDatabase,type Database } from '../packages/knowledge/src/database.js';
import { KnowledgeService } from '../packages/knowledge/src/service.js';
import { ProjectService } from '../packages/projects/src/service.js';
import { createSceneLabFixture } from './helpers/scenelab.js';
import { normalizedRequirement,userFactKey } from '../packages/projects/src/workspace.js';
import { emptyRequirements, extractRequirementsAI, parseRequirements } from '../packages/projects/src/requirements.js';
import { mergeWorkspaceRequirements } from '../packages/projects/src/workspace.js';
import type { ReconstructionReview } from '../packages/projects/src/reconstruction.js';
describe('requirement workspace evidence and lifecycle',()=>{
 let directory:string,db:Database,service:ProjectService;const objects=new Map<string,Uint8Array>();
 beforeAll(async()=>{directory=await mkdtemp(path.join(tmpdir(),'workspace-phase12-'));db=await openDatabase(directory);const knowledge=new KnowledgeService(db,directory,{put:async(k,b)=>{objects.set(k,b);},delete:async k=>{objects.delete(k);},get:async k=>{const b=objects.get(k);if(!b)throw new Error('Missing object');return b;}},()=>({generate:async()=>{throw new Error('No external API in regression');}}),true);await knowledge.settings.init();service=new ProjectService(db,knowledge);},30000);
 afterAll(async()=>{await db?.close();if(directory)await rm(directory,{recursive:true,force:true});});
 test('merges equivalent requirements, preserves conflicting alternatives and removes only deleted evidence',async()=>{
  const p=await service.create({name:'多来源回归'});const a=await service.addText(p.id,{text:'帧率>=180Hz。精度≤0.5mm。'});const b=await service.addText(p.id,{text:'帧率不得低于180Hz。精度≤1mm。'});
  const frame=b.context.workspaceRequirements!.find(r=>r.semanticKey==='performance.frameRate')!;expect(frame.evidenceRefs).toHaveLength(2);expect(frame.status).toBe('proposed');
  const accuracy=b.context.workspaceRequirements!.find(r=>r.semanticKey==='performance.accuracy')!;expect(accuracy.status).toBe('conflicted');expect(accuracy.alternatives).toHaveLength(2);expect(b.context.requirements.performance.accuracy).toBeUndefined();await expect(service.confirmContext(p.id,b.context.revision)).rejects.toMatchObject({statusCode:409});
  const chosen=await service.decideRequirement(p.id,accuracy.id,{choice:1});expect(chosen.requirements.performance.accuracy?.value).toContain('1mm');
  const removed=await service.removeInput(p.id,b.input.id);expect(removed.workspaceRequirements!.find(r=>r.semanticKey==='performance.frameRate')?.evidenceRefs).toHaveLength(1);expect(removed.requirements.performance.accuracy?.value).toContain('1mm');expect(removed.workspaceRequirements!.find(r=>r.id===accuracy.id)?.evidenceRefs.some(e=>e.sourceId===b.input.id)).toBe(false);
  await service.removeInput(p.id,a.input.id);expect((await service.getContext(p.id)).requirements.performance.frameRate).toBeUndefined();
 });
 test('manual notes preserve original text, facts and labels while answers route directly',async()=>{
  const p=await service.create({name:'说明回归'});const note=await service.saveNote(p.id,{title:'客户电话',text:'应用场景：机器人遥操作。相机数量：16台。场地12×10×5m。帧率≥180Hz。'});
  expect((await service.listNotes(p.id))[0].text).toContain('相机数量：16台');expect(note.context.fingerprint?.applications).toContain('robotics');expect(note.context.factProposals?.find(f=>f.key==='deployment.equipmentCount')?.value).toBe(16);
  const answer=await service.answerClarification(p.id,'missing-accuracy',{mode:'answer',value:'≤0.3mm'});expect(answer.requirements.performance.accuracy?.value).toBe('≤0.3mm');
  const unknown=await service.answerClarification(p.id,'missing-latency',{mode:'unknown'});expect(unknown.unresolved.find(q=>q.key==='latency')?.answerMode).toBe('unknown');
  const fact=await service.addFact(p.id,{label:'相机数量',value:16,unit:'台',category:'设备'});expect(fact.lockedFacts.find(f=>f.key==='deployment.equipmentCount')?.value).toBe(16);
  await service.saveNote(p.id,{text:'这次补充没有帧率参数',status:'archived'},note.note.id);expect((await service.getContext(p.id)).requirements.performance.frameRate).toBeUndefined();expect((await service.listNotes(p.id))[0].status).toBe('archived');
 });
 test('invalid replacement keeps original input, context and bytes; valid replacement removes old chunks',async()=>{
  const p=await service.create({name:'替换回归'}),original=await service.addText(p.id,{text:'建设目标：旧文件独有文本。帧率180Hz。'});const revision=original.context.revision,objectCount=objects.size;
  await expect(service.replaceInput(p.id,original.input.id,{filename:'bad.docx',bytes:Buffer.from('broken zip')})).rejects.toMatchObject({statusCode:400});expect(objects.size).toBe(objectCount);expect((await service.getContext(p.id)).revision).toBe(revision);expect((await service.downloadInput(p.id,original.input.id)).bytes).toEqual(Buffer.from('建设目标：旧文件独有文本。帧率180Hz。'));
  const replacement=await service.replaceInput(p.id,original.input.id,{filename:'replacement.txt',bytes:Buffer.from('建设目标：新版文件。帧率240Hz。')});expect(replacement.input.status).toBe('ready');expect(replacement.context.requirements.performance.frameRate?.value).toContain('240Hz');expect((await service.get(p.id)).inputs).toHaveLength(1);expect(await db.query('SELECT id FROM knowledge_chunks WHERE document_id=$1',[original.input.documentId])).toHaveLength(0);await expect(service.downloadInput(p.id,original.input.id)).rejects.toMatchObject({statusCode:404});
 });
 test('SceneLab deletion removes live engineering/assets without deleting another project or global data',async()=>{
  const a=await service.create({name:'报告回归'}),b=await service.create({name:'保留项目'});const report=await service.addInput(a.id,{filename:'test.scenelab-report',bytes:await createSceneLabFixture()});expect(report.context.engineering).toBeDefined();const beforeGlobal=await db.query("SELECT id FROM documents WHERE scope='global'");const removed=await service.removeInput(a.id,report.input.id);expect(removed.engineering).toBeUndefined();expect(removed.assets).toHaveLength(0);await service.remove(a.id);expect([...objects.keys()].some(k=>k.startsWith(`projects/${a.id}/`))).toBe(false);await expect(service.get(a.id)).rejects.toMatchObject({statusCode:404});expect((await service.get(b.id)).name).toBe('保留项目');expect(await db.query("SELECT id FROM documents WHERE scope='global'")).toEqual(beforeGlobal);
 });
 test('asset upload checks ownership and leaves confirmed understanding untouched',async()=>{
  const p=await service.create({name:'图片回归',description:'用于上传品牌图片'});const context=await service.getContext(p.id);await service.confirmContext(p.id,context.revision);const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jMd8AAAAASUVORK5CYII=','base64');const asset=await service.addAsset(p.id,{filename:'logo.png',buffer:png,role:'logo'});expect(asset.role).toBe('logo');expect(asset.width).toBe(1);expect((await service.getContext(p.id)).confirmed).toBe(true);expect((await service.getContext(p.id)).revision).toBe(context.revision);await expect(service.addAsset(p.id,{filename:'bad.png',buffer:Buffer.from('<script>bad</script>')})).rejects.toMatchObject({statusCode:400});
 });
 test('removing a manual override restores source evidence and preserves unrelated manual facts',async()=>{
  const p=await service.create({name:'人工值回归'});await service.addText(p.id,{text:'帧率≥180Hz。'});const confirmed=await service.addRequirement(p.id,{type:'frameRate',label:'帧率',value:'≥240Hz'});const row=confirmed.workspaceRequirements!.find(r=>r.category==='performance.frameRate')!;
  const restored=await service.clearRequirementValue(p.id,row.id);expect(restored.requirements.performance.frameRate?.value).toContain('180Hz');expect(restored.requirements.performance.frameRate?.confirmedByUser).toBe(false);
  const fact=await service.addFact(p.id,{label:'相机数量',value:'16台',unit:'台',category:'设备'});const user=fact.lockedFacts.find(f=>f.key==='deployment.equipmentCount')!;expect(user.value).toBe(16);const cleared=await service.removeFact(p.id,user.id);expect(cleared.lockedFacts.some(f=>f.id===user.id)).toBe(false);
 });
 test('normalization retains inequality direction',()=>{expect(normalizedRequirement('帧率不得低于180Hz')).toBe(normalizedRequirement('>=180Hz'));expect(normalizedRequirement('≤0.5mm')).not.toBe(normalizedRequirement('≥0.5mm'));});
 test('AI selection excludes heuristic headings and product metrics and retains all grounded alternatives',async()=>{
  const source={id:'xr-source',title:'xR 大空间虚拟拍摄',text:'建设目标\t3\n场地要求\t16\n本方案采用MC4000型号光学相机。\nLED刷新率至少为3840Hz，电影拍摄不低于7680Hz。\nMC4000极限有效捕捉距离为60M。\n客户帧率要求不低于180Hz。\n另一客户帧率要求不低于240Hz。',chunks:[]};
  const selected=await extractRequirementsAI([source],{generate:async()=>({content:JSON.stringify({items:[{category:'performance.frameRate',value:'不低于180Hz',sourceInputId:source.id,evidence:'客户帧率要求不低于180Hz。'},{category:'performance.frameRate',value:'不低于240Hz',sourceInputId:source.id,evidence:'另一客户帧率要求不低于240Hz。'}],facts:[{label:'相机型号',value:'MC4000',sourceInputId:source.id,evidence:'本方案采用MC4000型号光学相机。',category:'设备'}],tags:[{dimension:'products',value:'MC4000',sourceInputId:source.id,evidence:'本方案采用MC4000型号光学相机。'}]})})});
  const rows=mergeWorkspaceRequirements('project',[source],selected,[],[],[],[],selected.extractedItems,selected.aiReviewedSourceIds);expect(rows).toHaveLength(1);expect(rows[0].status).toBe('conflicted');expect(rows[0].alternatives?.map(a=>a.value)).toEqual(['不低于180Hz','不低于240Hz']);expect(selected.extractedFacts).toHaveLength(1);expect(selected.extractedFingerprint?.products).toEqual(['MC4000']);
  const reused=mergeWorkspaceRequirements('project',[source],emptyRequirements(),[],[],[],[],selected.extractedItems,selected.aiReviewedSourceIds);expect(reused).toEqual(rows);const heuristic=parseRequirements([source]);expect(heuristic.performance.range).toBeUndefined();expect(heuristic.goals).toHaveLength(0);expect(JSON.stringify(heuristic.performance)).not.toContain('3840');
 });
 test('later imports preserve AI-selected scope instead of reviving old heuristic matches',async()=>{
  const p=await service.create({name:'虚拟拍摄范围回归'});const input=await service.addText(p.id,{text:'建设目标：虚拟拍摄。手眼标定原理介绍机器人。LED刷新率至少为3840Hz。客户帧率要求不低于180Hz。'});const settings=service.knowledge.settings,previousConfig=settings.config;
  settings.config=async()=>({baseUrl:'https://api.moonshot.cn/v1',apiKey:'synthetic-test-key',model:'kimi-k3',temperature:1,maxTokens:131072});
  try{const ai=new ProjectService(db,service.knowledge,()=>({generate:async()=>({content:JSON.stringify({items:[{category:'performance.frameRate',sourceInputId:input.input.id,value:'不低于180Hz',evidence:'客户帧率要求不低于180Hz。'}],tags:[{dimension:'applications',sourceInputId:input.input.id,value:'虚拟拍摄',evidence:'建设目标：虚拟拍摄。'}]})})}));const selected=await ai.rebuildContext(p.id,{useAI:true});expect(selected.workspaceRequirements).toHaveLength(1);expect(selected.fingerprint?.applications).toEqual(['虚拟拍摄']);expect(selected.aiReviewedSourceIds).toEqual([input.input.id]);const later=await ai.addText(p.id,{text:'安装约束：墙体不可钻孔。'});expect(later.context.requirements.performance.frameRate?.value).toBe('不低于180Hz');expect(later.context.requirements.goals).toHaveLength(0);expect(later.context.fingerprint?.applications).toEqual(['虚拟拍摄']);expect(later.context.workspaceRequirements?.some(r=>String(r.value).includes('3840'))).toBe(false);}finally{settings.config=previousConfig;}
 });
 test('historical review replaces noise with sourced QA facts without claiming customer confirmation',async()=>{
  const p=await service.create({name:'历史复建测试',description:'[historical_reconstruction_only] 独立回归样例，非客户确认'}),text='本项目采用16台MC4000相机。\n客户要求完成动作采集。';const uploaded=await service.addText(p.id,{text});
  const version=(await db.query('SELECT id,parsed_document FROM document_versions WHERE document_id=$1',[uploaded.input.documentId]))[0];const block=version.parsed_document.blocks.findIndex((b:any)=>b.text.includes('16台MC4000'));const excerpt=version.parsed_document.blocks[block].text;
  const evidence={projectInputId:uploaded.input.id,sourceDocumentId:uploaded.input.documentId!,sourceVersionId:version.id,sourceBlockIndex:block,headingPath:[],excerpt};
  const payload:ReconstructionReview={revision:uploaded.context.revision,scope:'historical_reconstruction_only',reviewedBy:'Test source review',summary:'复建原有动作采集项目',products:['MC4000'],fingerprint:{applications:[],targetObjects:[],scenarios:[],topics:[],modules:[],products:['MC4000'],environment:[],constraints:[]},doNotClaim:['不能声明已通过数值精度验收'],requirements:[{category:'goals',label:'采集目标',value:'完成动作采集',evidence:{...evidence,sourceBlockIndex:version.parsed_document.blocks.findIndex((b:any)=>b.text.includes('客户要求')),excerpt:version.parsed_document.blocks.find((b:any)=>b.text.includes('客户要求')).text}}],facts:[{key:'deployment.equipmentCount',label:'原方案相机数量',value:16,unit:'台',evidence}]};
  const reviewed=await service.applyReconstructionReview(p.id,payload);expect(reviewed.reviewScope).toBe('historical_reconstruction_only');expect(reviewed.confirmed).toBe(true);expect(reviewed.requirements.goals).toHaveLength(1);expect(reviewed.requirements.goals[0].confirmedByUser).toBe(false);expect(reviewed.workspaceRequirements?.every(r=>!r.confirmedByUser&&r.evidenceRefs.every(e=>e.sourceType==='project_file'))).toBe(true);expect(reviewed.lockedFacts[0]).toMatchObject({sourceType:'historical_reconstruction',confirmedByUser:false,value:16,sourceRef:{type:'project_input',id:uploaded.input.id}});expect((await service.getContext(p.id)).confirmed).toBe(true);expect(await db.query("SELECT id FROM project_facts WHERE project_id=$1 AND source_type='user'",[p.id])).toHaveLength(0);
  const b=await service.create({name:'其他历史项目',description:'[historical_reconstruction_only] 回归'}),other=await service.addText(b.id,{text});const before=await service.getContext(b.id);await expect(service.applyReconstructionReview(b.id,{...payload,revision:before.revision})).rejects.toMatchObject({statusCode:400});expect((await service.getContext(b.id)).revision).toBe(before.revision);
  await expect(service.applyReconstructionReview(p.id,{...payload,revision:reviewed.revision,facts:[{...payload.facts[0],evidence:{...evidence,excerpt:'原文不存在的数字99台'}}]})).rejects.toMatchObject({statusCode:400});
  await expect(service.applyReconstructionReview(p.id,{...payload,revision:reviewed.revision,facts:[{...payload.facts[0],evidence:{...evidence,sourceVersionId:'forged-version'}}]})).rejects.toMatchObject({statusCode:400});
  const ordinary=await service.create({name:'真实客户项目'});await expect(service.applyReconstructionReview(ordinary.id,{...payload,revision:ordinary.contextRevision})).rejects.toMatchObject({statusCode:409});expect((await service.get(b.id)).inputs[0].id).toBe(other.input.id);
 });
 test('note revisions and confirmed factual source evidence remain traceable',async()=>{
  const p=await service.create({name:'资料追溯'});const original=await service.saveNote(p.id,{text:'相机数量：16台。'});const second=await service.saveNote(p.id,{title:'第二来源',text:'设备数量：16台。'});const proposal=second.context.factProposals!.find(f=>f.key==='deployment.equipmentCount')!;expect(proposal.evidenceRefs).toHaveLength(2);await service.addFact(p.id,{label:proposal.label,value:proposal.value,unit:proposal.unit,category:'设备',proposalId:proposal.id});
  const rebuilt=await service.rebuildContext(p.id);expect(rebuilt.lockedFacts.find(f=>f.key==='deployment.equipmentCount')?.evidenceRefs?.some(e=>e.sourceType==='manual_note'&&e.sourceId===original.note.id)).toBe(true);
  await service.saveNote(p.id,{text:'相机数量：20台。'},original.note.id);const audits=await db.query("SELECT previous_value FROM project_audit_events WHERE project_id=$1 AND action='note_saved' AND previous_value->>'text' IS NOT NULL",[p.id]);expect(audits[0].previous_value.text).toBe('相机数量：16台。');
 });
 test('automatic extraction rejects known absolute marketing targets while retaining numeric goals and user wording',async()=>{
  const values=['在当今全球范围内属于先进水平','选择具有最优性能价格比和扩充能力的产品','接口达到行业领先水准','系统能够在不受时间、环境条件限制的情况下持续稳定运行','客户目标：采集帧率不低于180Hz'];const source={id:'marketing',text:values.join('。'),chunks:[]};const extracted=await extractRequirementsAI([source],{generate:async()=>({content:JSON.stringify({items:values.map(value=>({category:'goals',value,sourceInputId:source.id,evidence:value}))})})});expect(extracted.goals.map(i=>i.value)).toEqual([values[4]]);
  const p=await service.create({name:'人工要求不会被广告词过滤'});const manual=await service.addRequirement(p.id,{type:'other',label:'客户原文',value:values[3]});expect(manual.workspaceRequirements?.some(r=>r.confirmedByUser&&r.value===values[3])).toBe(true);
 });
 test('complementary qualitative scopes merge evidence while genuinely different numeric targets still conflict',()=>{
  const sources=[{id:'a',text:'覆盖范围为实验墙主要区域。精度建设目标为亚毫米级定位。相机数量16台MC4000。',chunks:[]},{id:'b',text:'覆盖范围为墙前运行空间和8工位。精度目标为墙面亚毫米级定位。相机数量16台。',chunks:[]}];
  const records=[{category:'performance.coverage',value:'实验墙主要区域',source:'a'},{category:'performance.coverage',value:'墙前运行空间和8工位',source:'b'},{category:'performance.accuracy',value:'亚毫米级定位',source:'a'},{category:'performance.accuracy',value:'墙面亚毫米级定位',source:'b'},{category:'performance.cameraCount',value:'16台MC4000',source:'a'},{category:'performance.cameraCount',value:'16台',source:'b'}];
  const rows=mergeWorkspaceRequirements('qualitative',sources,emptyRequirements(),[],[],[],[],records.map((r,i)=>({category:r.category,item:{id:String(i),value:r.value,sourceInputId:r.source,evidence:sources.find(s=>s.id===r.source)!.text,confidence:.8,confirmedByUser:false}})),['a','b']);expect(rows).toHaveLength(3);expect(rows.every(r=>r.status==='proposed'&&r.evidenceRefs.length===2)).toBe(true);expect(rows.find(r=>r.category==='performance.coverage')?.value).toContain('8工位');expect(userFactKey('相机安装高度','工程')).toBe('deployment.installationHeight');expect(userFactKey('安装方式','设备')).toBe('installation.method');expect(userFactKey('场地尺寸','场地',[12,10,5])).toBe('scene.boundaryM');expect(userFactKey('总场地尺寸','场地','200m×200m')).not.toBe('scene.boundaryM');expect(userFactKey('总统府内部捕捉场地尺寸','场地','20米×20米')).not.toBe(userFactKey('总场地尺寸','场地','200m×200m'));expect(userFactKey('场地尺寸','场地','20m×20m')).not.toBe('scene.boundaryM');
 });
 test('qualitative scale or opposite conditions remain conflicts rather than assuming compatibility',()=>{
  for(const [category,a,b] of [['performance.accuracy','亚毫米级定位','厘米级定位'],['performance.coverage','室内运行','室外运行'],['performance.coverage','支持室外运行','不支持室外运行']]){const sources=[{id:'a',text:a,chunks:[]},{id:'b',text:b,chunks:[]}];const rows=mergeWorkspaceRequirements('opposites',sources,emptyRequirements(),[],[],[],[],sources.map((s,i)=>({category,item:{id:String(i),value:s.text,sourceInputId:s.id,evidence:s.text,confidence:.8,confirmedByUser:false}})),['a','b']);expect(rows[0].status).toBe('conflicted');expect(rows[0].alternatives).toHaveLength(2);}
 });
});
