import {useEffect,useRef,useState} from 'react';
import {ChevronDown,ChevronRight,List,LoaderCircle} from 'lucide-react';
import type {DocumentSection} from '../../../packages/document-engine/src/types.js';
export function visibleOutline(sections:DocumentSection[],collapsed:Set<string>){let hidden=false;return sections.filter(s=>{if(s.level===1){hidden=collapsed.has(s.id);return true;}return !hidden;});}
export function DocumentOutline({sections,selectedId,onSelect,onPlan}:{sections:DocumentSection[];selectedId?:string;onSelect:(id:string)=>void;onPlan:()=>void}){
 const [collapsed,setCollapsed]=useState(new Set<string>()),nav=useRef<HTMLElement>(null);
 useEffect(()=>{const fit=()=>{const panel=nav.current;if(panel)panel.parentElement?.style.setProperty('--editor-side-height',`${Math.max(200,window.innerHeight-Math.max(85,panel.getBoundingClientRect().top)-20)}px`);};fit();window.addEventListener('resize',fit);window.addEventListener('scroll',fit,true);return()=>{window.removeEventListener('resize',fit);window.removeEventListener('scroll',fit,true);};},[]);
 useEffect(()=>{const index=sections.findIndex(s=>s.id===selectedId);let parent:DocumentSection|undefined;for(let i=index;i>=0;i--)if(sections[i].level===1){parent=sections[i];break;}if(parent)setCollapsed(old=>{const next=new Set(old);next.delete(parent!.id);return next;});},[selectedId]);
 useEffect(()=>{const node=nav.current?.querySelector<HTMLElement>('[aria-current="true"]');if(node&&nav.current){const frame=nav.current,nodeRect=node.getBoundingClientRect(),frameRect=frame.getBoundingClientRect();if(nodeRect.top<frameRect.top+50)frame.scrollTop+=nodeRect.top-frameRect.top-50;else if(nodeRect.bottom>frameRect.bottom)frame.scrollTop+=nodeRect.bottom-frameRect.bottom;}},[selectedId,collapsed]);
 return <nav ref={nav} className="panel document-outline" aria-label="方案章节"><header><h2>章节</h2><button className="icon-button" aria-label="调整章节计划" onClick={onPlan}><List size={16}/></button></header>{visibleOutline(sections,collapsed).map(section=><div className="outline-row" key={section.id}><button className={`document-outline-item ${selectedId===section.id?'active':''}`} aria-current={selectedId===section.id} style={{paddingLeft:`${12+(section.level-1)*10}px`}} onClick={()=>onSelect(section.id)}><span>{sections.indexOf(section)+1}</span><span><strong>{section.title}</strong><small>{({empty:'待生成',queued:'排队中',generating:'生成中',generated:'已生成',edited:'人工编辑',validated:'已校验',failed:'生成失败'})[section.status]}</small></span>{section.status==='generating'&&<LoaderCircle className="spin" size={13}/>}</button>{section.level===1&&<button className="outline-collapse icon-button" aria-label={`${collapsed.has(section.id)?'展开':'收起'}${section.title}`} aria-expanded={!collapsed.has(section.id)} onClick={()=>setCollapsed(old=>{const next=new Set(old);next.has(section.id)?next.delete(section.id):next.add(section.id);return next;})}>{collapsed.has(section.id)?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</button>}</div>)}</nav>;
}
