import { useState } from 'react';
import { BookOpen, ChevronRight, Sparkles, Star } from 'lucide-react';
import {tagDimensions,type TagDimension,type AliasSuggestion,type EnrichmentBatch,type EnrichmentItem,type KnowledgeSection,type ReferenceQuality,type SoftTags} from '../../../packages/knowledge-enrichment/src/types.js';
import { tagLabel } from '../../../packages/knowledge-enrichment/src/taxonomy.js';
import type { DocumentSelection } from './Refinement.js';
import { patch, post } from './api.js';
import { ErrorMessage, Loading, Modal, date, useResource, type Notify } from './ui.js';
import './knowledge-enrichment.css';

const statuses:Record<string,string>={queued:'排队中',running:'整理中',completed:'已完成',partially_failed:'部分完成',failed:'未完成',stale:'来源已更新',cancelled:'已取消'};
const qualities:[ReferenceQuality,string][]=[['normal','☆ 普通'],['good','★ 优质参考'],['preferred','★★ 首选参考']];
const dimensionNames:Record<string,string>={document_type:'资料类型',applications:'应用领域',target_objects:'应用对象',scenarios:'项目场景',technical_topics:'技术主题',system_modules:'系统模块',products:'产品',project_stage:'项目阶段',environment:'环境',constraints:'约束',deliverables:'交付成果'};
interface EnrichmentView {documentId:string;title:string;versionId:string;quality:ReferenceQuality;tags:SoftTags;enrichedAt:string|null;sections:KnowledgeSection[]}
export function QualitySelector({value,change,label='参考质量',disabled=false}:{value:ReferenceQuality;change:(quality:ReferenceQuality)=>void;label?:string;disabled?:boolean}){return <label className="knowledge-quality"><span>{label}</span><select aria-label={label} value={value} disabled={disabled} onChange={event=>change(event.target.value as ReferenceQuality)}>{qualities.map(([quality,label])=><option key={quality} value={quality}>{label}</option>)}</select></label>;}
function SoftTagList({tags}:{tags:SoftTags}){return <div className="enrichment-tags">{Object.entries(tags).filter(([,values])=>values?.length).map(([dimension,values])=><div key={dimension}><strong>{dimensionNames[dimension]??dimension}</strong><span>{values?.map(tag=><span className={`tag ${tag.confidence<.8?'uncertain-tag':''}`} key={tag.value} title={`整理置信度 ${Math.round(tag.confidence*100)}%${tag.confidence<.8?'，检索时降低权重':''}`}>{tagLabel(dimension,tag.value)}{tag.confidence<.8?' · 低置信度':''}</span>)}</span></div>)}</div>;}

export function KnowledgeSections({documentId,close,notify}:{documentId:string;close:()=>void;notify:Notify}){
 const resource=useResource<EnrichmentView>(`/documents/${documentId}/enrichment`,0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState<string>();
 const change=async(path:string,quality:ReferenceQuality)=>{setBusy(true);setError('');try{await patch(path,{quality});resource.reload();notify('参考质量已更新，后续章节推荐将使用新的优先级。');}catch(error){setError(error instanceof Error?error.message:'保存失败');}finally{setBusy(false);}};
 return <Modal title="历史章节与参考质量" close={close} className="enrichment-modal"><div className="enrichment-body">{(error||resource.error)&&<ErrorMessage message={error||resource.error}/>} {!resource.data?<Loading/>:<>
  <div className="enrichment-document-heading"><div><h3>{resource.data.title}</h3><p>{resource.data.enrichedAt?`整理于 ${date(resource.data.enrichedAt)}`:'尚未深度整理，可先设置整份资料的参考优先级。'}</p></div><QualitySelector value={resource.data.quality} disabled={busy} change={quality=>void change(`/documents/${documentId}/reference-quality`,quality)}/></div>
  <SoftTagList tags={resource.data.tags}/>
  <p className="muted">历史章节用于组织结构、通用技术逻辑和表达方法。当前项目的台数、场地和产品参数使用当前项目自己的依据。</p>
  {!resource.data.sections.length&&<div className="enrichment-empty">在资料库选择该资料后，点击“AI 深度整理”生成完整历史章节。</div>}
  <div className="enrichment-sections">{resource.data.sections.map(section=><article key={section.id}><header><button className="text-button enrichment-section-title" onClick={()=>setExpanded(expanded===section.id?undefined:section.id)} aria-expanded={expanded===section.id}><ChevronRight size={15} className={expanded===section.id?'rotated':''}/><span>{section.headingPath.join(' / ')||section.title}</span></button><span className="tag">{tagLabel('section_role',section.sectionRole)}</span><QualitySelector label={`“${section.title}”参考质量`} value={section.quality} disabled={busy} change={quality=>void change(`/knowledge-sections/${section.id}/reference-quality`,quality)}/></header><p>{section.summary}</p>{expanded===section.id&&<><SoftTagList tags={section.softTags}/><div className="enrichment-blueprint"><h4>可复用写法</h4><p>{section.blueprint.purpose}</p><ol>{section.blueprint.recommendedStructure.map((text,index)=><li key={index}>{text}</li>)}</ol><ul>{section.blueprint.reusableTechnicalLogic.map((text,index)=><li key={index}>{text}</li>)}</ul>{section.blueprint.expectedFacts.length>0&&<p><strong>新项目需要的事实：</strong>{section.blueprint.expectedFacts.join('、')}</p>}{section.blueprint.projectSpecificElements.length>0&&<p><strong>原项目专属内容：</strong>{section.blueprint.projectSpecificElements.join('、')}</p>}</div><details><summary>查看完整原始章节</summary><pre className="knowledge-section-source">{section.text}</pre></details></>}</article>)}</div>
 </>}</div></Modal>;
}

export function EnrichmentDialog({selection,selectedCount,filters,close,notify,onComplete}:{selection:DocumentSelection;selectedCount:number;filters:Record<string,string>;close:()=>void;notify:Notify;onComplete:()=>void}){
 const [scope,setScope]=useState<'selected'|'filtered'|'all'>(selectedCount?'selected':'filtered'),[budget,setBudget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[batchId,setBatchId]=useState<string>(),[documentId,setDocumentId]=useState<string>();
 const history=useResource<{items:EnrichmentBatch[]}>('/enrichment/batches',0,4000),result=useResource<{batch:EnrichmentBatch;items:EnrichmentItem[]}>(batchId?`/enrichment/batches/${batchId}`:null,0,2500),aliases=useResource<{items:AliasSuggestion[]}>('/enrichment/aliases',0,6000);
 const run=async()=>{setBusy(true);setError('');try{const response=await post<{batch:EnrichmentBatch}>('/enrichment/batches',{...(scope==='selected'?selection:{selection:{mode:scope,...(scope==='filtered'?{filters}:{})}}),budgetCny:budget.trim()?Number(budget):null});setBatchId(response.batch.id);history.reload();notify('已加入 Kimi K3 深度整理队列，可关闭窗口继续工作。');}catch(error){setError(error instanceof Error?error.message:'启动失败');}finally{setBusy(false);}};
 const decideAlias=async(id:string,accept:boolean,dimension?:TagDimension)=>{setBusy(true);setError('');try{await post(`/enrichment/aliases/${id}/${accept?'accept':'reject'}`,accept?{dimension}:undefined);aliases.reload();notify(accept?'同义标签已归并，项目画像与知识检索将统一匹配。':'已忽略此建议。');}catch(error){setError(error instanceof Error?error.message:'操作失败');}finally{setBusy(false);}};
 const cancel=async()=>{if(!batchId)return;setBusy(true);try{await post(`/enrichment/batches/${batchId}/cancel`);result.reload();}catch(error){setError(error instanceof Error?error.message:'取消失败');}finally{setBusy(false);}};
 if(documentId)return <KnowledgeSections documentId={documentId} close={()=>setDocumentId(undefined)} notify={notify}/>;
 return <Modal title="AI 深度整理" close={()=>{onComplete();close();}} className="enrichment-modal"><div className="enrichment-body"><p className="enrichment-intro"><Sparkles size={20}/>用 Kimi K3 为资料整理多维标签、完整历史章节、章节用途和可复用写法，供方案写作匹配。</p><div className="enrichment-options"><label>整理范围<select value={scope} onChange={event=>setScope(event.target.value as typeof scope)}><option value="selected" disabled={!selectedCount}>所选资料（{selectedCount} 份）</option><option value="filtered">当前筛选结果</option><option value="all">全部可整理资料</option></select></label><label>可选本批预算（元）<input type="number" min="0.01" step="1" value={budget} placeholder="默认不限制" onChange={event=>setBudget(event.target.value)}/></label><button className="button primary" disabled={busy||(scope==='selected'&&!selectedCount)} onClick={()=>void run()}><Sparkles size={15}/>开始深度整理</button></div><p className="muted">高置信度标签自动使用；低置信度标签会保留并降低推荐权重。正式分类、资料权威级别与产品参数保持人工确认规则。</p>
  {(error||history.error||result.error)&&<ErrorMessage message={error||history.error||result.error}/>}
  {!!history.data?.items.length&&<label className="enrichment-history">整理任务<select value={batchId??''} onChange={event=>setBatchId(event.target.value||undefined)}><option value="">查看最近任务</option>{history.data.items.map(batch=><option value={batch.id} key={batch.id}>{date(batch.createdAt)} · {batch.total} 份 · {statuses[batch.status]}</option>)}</select></label>}
  {result.data&&<section className="enrichment-progress"><header><h3>{statuses[result.data.batch.status]} · {result.data.batch.processed}/{result.data.batch.total} 份</h3>{['queued','running'].includes(result.data.batch.status)&&<button className="text-button" disabled={busy} onClick={()=>void cancel()}>取消排队资料</button>}</header><progress max={result.data.batch.total} value={result.data.batch.processed+result.data.batch.failed}/><p>{result.data.batch.model} · 已返回用量 {result.data.batch.inputTokens.toLocaleString()} 输入 / {result.data.batch.outputTokens.toLocaleString()} 输出 · 本批费用估算 ¥{result.data.batch.estimatedCostCny.toFixed(3)} · {result.data.batch.budgetCny===null?'未设置预算限制':`预算 ¥${result.data.batch.budgetCny}`}</p><div className="enrichment-items">{result.data.items.map(item=><article key={item.id}><div><strong>{item.documentTitle}</strong><span>{statuses[item.status]??item.status}{item.sectionCount?` · ${item.sectionCount} 个完整章节`:''}</span>{item.error&&<p className="muted-danger">{item.error}</p>}</div>{item.status==='completed'&&<button className="button small-button" onClick={()=>setDocumentId(item.documentId)}><BookOpen size={14}/>查看章节与星标</button>}</article>)}</div></section>}
  {!!aliases.data?.items.filter(item=>item.status==='pending').length&&<section className="enrichment-aliases"><h3>同义标签归并建议</h3><p className="muted">确认一次后，同义写法将统一参与项目匹配。模型未注明分类的建议，需要选择归并维度。</p>{aliases.data.items.filter(item=>item.status==='pending').map(item=><AliasReview key={item.id} item={item} busy={busy} accept={dimension=>void decideAlias(item.id,true,dimension)} reject={()=>void decideAlias(item.id,false)}/>)}</section>}
 </div></Modal>;
}

function AliasReview({item,busy,accept,reject}:{item:AliasSuggestion;busy:boolean;accept:(dimension:TagDimension)=>void;reject:()=>void}){const [dimension,setDimension]=useState<TagDimension|''>(item.dimension==='unassigned'?'':item.dimension);return <article><div><strong>{item.aliases.join('、')} → {tagLabel(item.dimension,item.canonical)}</strong><p>{item.reason}</p>{item.dimension==='unassigned'&&<label>归并维度 <select aria-label={`“${item.canonical}”归并维度`} value={dimension} onChange={event=>setDimension(event.target.value as TagDimension)}><option value="">请选择</option>{tagDimensions.map(value=><option key={value} value={value}>{dimensionNames[value]??value}</option>)}</select></label>}</div><button className="button small-button" disabled={busy||!dimension} onClick={()=>dimension&&accept(dimension)}>确认归并</button><button className="text-button" disabled={busy} onClick={reject}>忽略</button></article>;}

/** Visible from the library without changing the document detail drawer. */
export function ReferenceQualityShelf({documents,notify}:{documents:{id:string;title:string}[];notify:Notify}){const [open,setOpen]=useState(false),[documentId,setDocumentId]=useState<string>();return <><button className="text-button" onClick={()=>setOpen(!open)} aria-expanded={open}><Star size={14}/>章节与参考质量</button>{open&&<div className="reference-quality-shelf"><p>打开资料的完整历史章节，为优质内容标记优先级。</p>{documents.map(document=><button className="button small-button" key={document.id} onClick={()=>setDocumentId(document.id)}><BookOpen size={14}/>{document.title}</button>)}</div>}{documentId&&<KnowledgeSections documentId={documentId} close={()=>setDocumentId(undefined)} notify={notify}/>}</>;}
