import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCheck, ChevronDown, Clock3, FileText, Filter, Search, SlidersHorizontal, X } from 'lucide-react';
import type { DocumentRecord, KnowledgeChunk, Registries, Settings } from '../../../packages/core/src/types.js';
import { AuthorityBadge, Confidence, DocumentTable, Empty, ErrorMessage, FileIcon, Loading, Status, Tags, authorities, date, label, number, sourceLabels, useDebounce, useResource, type Stats } from './ui.js';

type Filters = { documentType: string; application: string; topic: string; product: string; authority: string; source: string; status: string };
const defaultFilters: Filters = { documentType: '', application: '', topic: '', product: '', authority: '', source: '', status: 'active' };
interface SearchResult { document: DocumentRecord; chunk: KnowledgeChunk; score: number }

export default function Library({ registries, settings, refresh, open, onUpload }: { registries?: Registries; settings?: Settings; refresh: number; open: (id: string, tab?: 'overview' | 'chunks') => void; onUpload: () => void }) {
  const [query, setQuery] = useState('');
  const debounced = useDebounce(query);
  const [filters, setFilters] = useState<Filters>(defaultFilters);
  const [expanded, setExpanded] = useState(false);
  const [page, setPage] = useState(1);
  const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value));
  params.set('page', String(page)); params.set('pageSize', '25');
  if (debounced.trim()) params.set('q', debounced.trim());
  const docs = useResource<{ items: DocumentRecord[]; total: number; page: number; pageSize: number }>(debounced.trim() ? null : `/documents?${params}`, refresh, 10000);
  const search = useResource<{ items: SearchResult[]; total: number }>(debounced.trim() ? `/search?${params}` : null, refresh);
  const result = debounced.trim() ? search : docs;
  const count = result.data?.total || 0;
  const filterCount = Object.entries(filters).filter(([key, value]) => value && (key !== 'status' || value !== 'active')).length;
  const changeFilter = (key: keyof Filters, value: string) => { setFilters(current => ({ ...current, [key]: value })); setPage(1); };
  const registrySelect = (key: 'documentType' | 'application' | 'topic', title: string, items?: { key: string; label: string }[]) => <label className="filter-select"><span className="sr-only">{title}</span><select value={filters[key]} onChange={event => changeFilter(key, event.target.value)}><option value="">全部{title}</option>{items?.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select><ChevronDown size={13} /></label>;
  return <>
    <div className="page-heading"><div><div className="eyebrow">A PLACE FOR WHAT YOU KNOW</div><h1>资料库<span className="heading-dot">.</span></h1><p>让经验可检索，让每一个答案有来源。</p></div><div className="heading-label"><BookOpen size={17} />已整理的知识</div></div>
    <section className="panel library-panel"><div className="library-toolbar"><div className="search-input"><Search size={19} /><input placeholder="搜索资料、产品或技术关键词…" aria-label="搜索资料" value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} />{query && <button className="icon-button" onClick={() => { setQuery(''); setPage(1); }} aria-label="清空搜索"><X size={15} /></button>}<kbd>全文检索</kbd></div><button className={`button ${expanded ? 'selected' : ''}`} onClick={() => setExpanded(value => !value)} aria-expanded={expanded}><SlidersHorizontal size={16} />筛选{filterCount > 0 && <span className="button-counter">{filterCount}</span>}</button></div>
      <div className="filter-bar">{registrySelect('documentType', '类型', registries?.documentTypes)}{registrySelect('application', '领域', registries?.applications)}{registrySelect('topic', '主题', registries?.topics)}<label className="filter-select"><span className="sr-only">权威级别</span><select value={filters.authority} onChange={event => changeFilter('authority', event.target.value)}><option value="">全部权威级别</option>{Object.entries(authorities).map(([key, value]) => <option value={key} key={key}>{value}</option>)}</select><ChevronDown size={13} /></label><span className="filter-spacer" /><span className="result-count">{number(result.data?.total)} {debounced ? '个匹配片段' : '份资料'}</span></div>
      {expanded && <div className="advanced-filters"><label>产品<input value={filters.product} placeholder="例如：产品型号" onChange={event => changeFilter('product', event.target.value)} /></label><label>资料来源<select value={filters.source} onChange={event => changeFilter('source', event.target.value)}><option value="">全部来源</option>{settings?.sources.map(source => <option value={source.id} key={source.id}>{source.name}</option>)}</select></label><label>资料状态<select value={filters.status} onChange={event => changeFilter('status', event.target.value)}><option value="active">已入库</option><option value="">全部状态</option><option value="needs_review">待确认</option><option value="failed">处理失败</option><option value="archived">已归档</option></select></label><button className="text-button" onClick={() => { setFilters(defaultFilters); setPage(1); }}>重置筛选</button></div>}
      {result.error && <ErrorMessage message={result.error} retry={result.reload} />}
      {result.loading ? <Loading text={debounced ? '正在检索知识片段…' : '正在读取资料库…'} /> : debounced.trim() ? search.data?.items.length ? <div className="search-results">{search.data.items.map(({ document: doc, chunk, score }) => <button className="search-result" key={`${doc.id}-${chunk.id}`} onClick={() => open(doc.id, 'chunks')}><div className="search-result-head"><FileIcon filename={doc.filename} small /><strong>{doc.title || doc.filename}</strong><span className="search-score">相关度 {Number(score).toFixed(2)}</span></div><div className="search-filename">{doc.filename}</div><div className="search-path"><span>{chunk.headingPath?.join(' / ') || '正文'}</span><span>片段 {chunk.order + 1} · v{doc.versionNumber}</span></div><p className="search-excerpt">{chunk.summary || chunk.text?.slice(0, 360)}</p><div className="search-result-meta"><span>{label(registries?.documentTypes, doc.classification?.documentType.value)}</span><AuthorityBadge value={doc.classification?.authority.value} /><Tags values={chunk.topics} registry={registries?.topics} max={3} /><span className="filter-spacer" /><span>{sourceLabels[doc.sourceType] || doc.sourceType}</span><ArrowRight size={14} /></div></button>)}</div> : <Empty title="还没有找到匹配的资料" text="试试更短的关键词、产品型号，或减少筛选条件。" /> : docs.data?.items.length ? <DocumentTable documents={docs.data.items} registries={registries} open={open} /> : <Empty title={filterCount ? '没有符合筛选条件的资料' : '把散落的经验，收进资料库'} text={filterCount ? '调整筛选条件，或查看其他资料状态。' : '已确认的资料会出现在这里，并支持全文检索与来源追踪。'}><button className="button" onClick={filterCount ? () => setFilters(defaultFilters) : onUpload}>{filterCount ? '清除筛选' : '导入第一份资料'}<ArrowRight size={14} /></button></Empty>}
      <div className="panel-footer"><span><span className="live-dot" />{filters.status === 'active' ? '当前仅检索已入库的有效版本' : '根据所选状态筛选资料'}</span>{count > 25 ? <div className="pagination"><button className="icon-button" disabled={page <= 1} aria-label="上一页" onClick={() => setPage(value => value - 1)}><ArrowLeft size={14} /></button><span>{page} / {Math.ceil(count / 25)}</span><button className="icon-button" disabled={page >= Math.ceil(count / 25)} aria-label="下一页" onClick={() => setPage(value => value + 1)}><ArrowRight size={14} /></button></div> : <span>原始资料始终可追溯</span>}</div>
    </section>
    <div className="library-note"><Filter size={15} /><p><strong>从问题找到知识。</strong> 关键词会同时匹配资料正文与知识片段。使用类型、领域和权威级别，进一步缩小范围。</p></div>
  </>;
}

export function Review({ registries, refresh, open, stats }: { registries?: Registries; refresh: number; open: (id: string) => void; stats?: Stats }) {
  const [page, setPage] = useState(1);
  const { data, loading, error, reload } = useResource<{ items: DocumentRecord[]; total: number }>(`/documents?status=needs_review&page=${page}&pageSize=20`, refresh, 6000);
  return <>
    <div className="page-heading"><div><div className="eyebrow">A LITTLE HUMAN JUDGMENT</div><h1>待确认<span className="heading-dot">.</span></h1><p>你只需要处理少数关键判断，其他交给系统。</p></div><span className="heading-label amber-text"><ListCheckIcon />{number(stats?.needsReview)} 项待确认</span></div>
    <div className="review-explainer"><span className="explainer-icon"><CheckCheck size={24} /></span><div><h2>每一次确认，都让整理更准确。</h2><p>只确认文档类型和权威级别。你的判断会作为后续相似资料的分类参考。</p></div><div className="example-count"><strong>{number(stats?.confirmedExamples)}</strong><span>已积累确认样例</span></div></div>
    {error && <ErrorMessage message={error} retry={reload} />}
    {loading && !data ? <Loading /> : data?.items.length ? <div className="review-list">{data.items.map((doc, index) => <article className="review-card" key={doc.id}><div className="review-card-top"><FileIcon filename={doc.filename} /><div className="review-card-title"><div><span className="review-sequence">{String((page - 1) * 20 + index + 1).padStart(2, '0')}</span><Status status="needs_review" /></div><h2>{doc.title || doc.filename}</h2><p>{doc.filename} <span>·</span> {sourceLabels[doc.sourceType] || doc.sourceType} <span>·</span> {date(doc.updatedAt)}</p></div></div>{doc.summary && <p className="review-summary">{doc.summary}</p>}<div className="review-fields"><div><span>文档类型</span><strong>{label(registries?.documentTypes, doc.classification?.documentType.value)}</strong><Confidence field={doc.classification?.documentType} /></div><div><span>权威级别</span><AuthorityBadge value={doc.classification?.authority.value} /><Confidence field={doc.classification?.authority} /></div></div><div className="review-card-bottom"><div><Clock3 size={14} /><span>{doc.reviewReasons.length ? doc.reviewReasons.join('；') : '有关键字段需要人工判断'}</span></div><button className="button primary" onClick={() => open(doc.id)}>查看并确认 <ArrowRight size={15} /></button></div></article>)}</div> : <section className="panel"><Empty title="所有判断，都已妥善完成" text="暂时没有需要确认的资料。新资料中不确定的关键字段会自动出现在这里。" /></section>}
    {!!data && data.total > 20 && <div className="pagination review-pagination"><button className="button" disabled={page <= 1} onClick={() => setPage(value => value - 1)}><ArrowLeft size={14} />上一页</button><span>{page} / {Math.ceil(data.total / 20)}</span><button className="button" disabled={page >= Math.ceil(data.total / 20)} onClick={() => setPage(value => value + 1)}>下一页<ArrowRight size={14} /></button></div>}
  </>;
}

function ListCheckIcon() { return <FileText size={16} />; }
