import type {DocumentTemplate,DocumentTemplateSection} from './types.js';
const section=(id:string,title:string,level:number,context:string[],extra:Partial<DocumentTemplateSection>={}):DocumentTemplateSection=>({id,title,level,order:0,generationMode:'ai',requiredContext:context,retrievalPolicy:{query:title,limit:6},generationInstruction:'依据来源编写完整、具体、可交付的中文技术方案，围绕本章解释设计依据、方法、系统关系与适用边界。区分客户目标、理论工程结果和有依据的产品能力；未知数值不写，其他内容围绕功能和设计方法展开，不编造工程决策。',...extra});
export const standardTemplate:DocumentTemplate={id:'standard-technical-proposal',name:'标准技术方案 · 光学动作捕捉',version:4,documentType:'technical_proposal',sections:[
 section('overview','项目概述',1,['summary','requirements']),
 section('requirements','项目需求理解',1,['requirements'],{generationMode:'fixed',fixedContent:'本章阐述应用需求与建设目标，明确系统设计的技术方向。'}),
 section('background','应用背景',2,['summary','requirements']),
 section('objectives','建设目标',2,['requirements']),
 section('indicators','关键技术指标',2,['requirements'],{generationMode:'table',tableKind:'requirements'}),
 section('architecture','总体技术方案',1,['summary'],{generationMode:'fixed',fixedContent:'系统设计围绕项目应用需求组织硬件、软件和数据链路。'}),
 section('system-architecture','系统总体架构',2,['requirements','engineering','products'],{retrievalPolicy:{query:'系统 架构 动作捕捉'},visualPlan:{type:'mermaid',description:'系统模块及其数据关系'}}),
 section('technical-route','技术路线',2,['requirements'],{retrievalPolicy:{query:'光学 动作捕捉 标定'}}),
 section('components','系统组成',2,['engineering','products'],{generationMode:'mixed',tableKind:'equipment',retrievalPolicy:{query:'系统组成 动作捕捉'}}),
 section('design','动作捕捉系统设计',1,['engineering'],{generationMode:'fixed',fixedContent:'本章说明系统设计依据与关键设计内容。'}),
 section('deployment','相机部署设计',2,['engineering'],{condition:'engineering',generationMode:'mixed',assetRoles:['deployment_perspective'],retrievalPolicy:{query:'相机 部署 安装'}}),
 section('coverage','捕捉覆盖设计',2,['engineering'],{condition:'engineering',generationMode:'mixed',assetRoles:['coverage_top','coverage_perspective'],tableKind:'engineering',retrievalPolicy:{query:'覆盖 遮挡'}}),
 section('accuracy','理论精度分析',2,['engineering','requirements'],{condition:'engineering',generationMode:'mixed',assetRoles:['accuracy_perspective','accuracy_front','accuracy_side'],tableKind:'engineering',retrievalPolicy:{query:'精度 理论 误差'}}),
 section('marker','Marker / 刚体设计',2,['requirements'],{retrievalPolicy:{query:'Marker 刚体 标记点'}}),
 section('hardware','系统硬件组成',1,['products','engineering'],{generationMode:'table',tableKind:'equipment'}),
 section('cameras','动捕相机',2,['products','engineering'],{generationMode:'mixed',tableKind:'products',retrievalPolicy:{query:'动捕 相机'}}),
 section('synchronization','同步系统',2,['products','requirements'],{retrievalPolicy:{query:'同步 系统'}}),
 section('network','网络与计算设备',2,['requirements','products'],{retrievalPolicy:{query:'网络 计算 配置'}}),
 section('software','软件系统',1,['requirements'],{generationMode:'fixed',fixedContent:'软件系统涵盖采集、数据处理及外部接口。'}),
 section('mocap-software','动捕软件',2,['requirements'],{retrievalPolicy:{query:'动捕 软件'}}),
 section('processing','数据处理',2,['requirements'],{retrievalPolicy:{query:'数据 处理 导出'}}),
 section('sdk','SDK 及接口',2,['requirements','products'],{retrievalPolicy:{query:'SDK 接口 协议'}}),
 section('data-link','系统同步与数据链路',1,['requirements','products'],{retrievalPolicy:{query:'同步 数据 传输'}}),
 section('installation','安装与部署设计',1,['requirements','engineering'],{retrievalPolicy:{query:'安装 部署 标定'}}),
 section('features','系统方案特点',1,['requirements','engineering','products'],{retrievalPolicy:{query:'动作捕捉 技术 特点'}}),
].map((s,order)=>({...s,order}))};
